### PR TITLE
Fix erroneously failing ChainDB QSM test

### LINKED ISSUE #3999: Debug ChainDB QSM failure where only the SUT iterator is exhausted
```
$ (cd ouroboros-network; git lg -1; git status -suno)
407146bdb - (HEAD, origin/master, origin/bors/staging, origin/HEAD) Merge #3996 (12 hours ago) <iohk-bors[bot]>

$ cabal run test-storage -- -p 'ChainDB q-s-m' --quickcheck-replay=845234
```

That fails (after about 10seconds of test execution) with:

```
    Resp {getResp = Right (IterResultGCed (IteratorResultGCed {real = True , iterResult = IteratorExhausted}))}
:/= Resp {getResp = Right (IterResultGCed (IteratorResultGCed {real = False, iterResult = IteratorResult ...}))}
```

This Issue is to determine the cause of the failure (I suggest checking for related comments/TODOs in the test code) and fix it.

### PR DESCRIPTION
**Pull request by bartfrenk**
# Description

There is a difference in behaviour of iterator over dead forks between the ChainDB state machine model and the system-under-test. The reason is that the iterator for the model does not take into account that blocks on a dead fork might have been garbage collected. This PR does two things:
- Adapt the model to take into account potentially garbage-collected blocks in its iterator implementation
- Add a unit test to bound the behaviour of iterators over dead forks for the system-under-test and the model.

Closes #3999.

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [x] The documentation has been properly updated

- Pull Request
    - [x] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs [hunk 1]
```diff
@@ -82,13 +100,84 @@ ouroboros_network_4183 =
...
+    void $ addBlock $ mkNextBlock b6 6 $ fork 2
+    persistBlks GarbageCollect
+
+    -- b1 is part of the current chain, so should always be streamed
+    iteratorNext i >>= hasResult b1
+
+    -- the remainder of the range of the iterator consists of blocks that may
+    -- have been garbage collected.
+    let expected = [blockRealPoint b2, blockRealPoint b3]
+    remainder <- allResults (length expected + 1) i
```
Comment (abailly-iohk) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs:134]: Why make `allResults` a generic function? We know the length of expected blocks here

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs [hunk 2]
```diff
@@ -82,13 +100,84 @@ ouroboros_network_4183 =
...
+    fork i = TestBody i True
+
+    extractBlock (blk, _, _, _, _, _, _, _, _, _, _) = blk
+
+    hasResult expected (API.IteratorResult actual) =
+      assertEqual expected (extractBlock actual) "Wrong block"
+    hasResult _ _ = failWith "Expected IteratorResult"
+
+    -- Bound the number of iterations by `maxIter` to avoid test stalling
+    allResults maxIter it = go maxIter
```
Comment (abailly-iohk) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs:148]: It seems to me we know exactly what each iterator should return, it would make the test clearer to explicitly list the result. Or perhaps there's seom form of non-determinism here?

**Review by abailly-iohk — APPROVED** [review]
I like the fact there's a unit test to assert the consistency of the model and the SUT. Some suggestions and questions but feel free to ignore those.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs [hunk 3]
```diff
@@ -82,13 +100,84 @@ ouroboros_network_4183 =
...
+                  _ -> pure []
+               else pure []
+
+    inclusiveFrom      = StreamFromInclusive . blockRealPoint
+
+    inclusiveTo        = StreamToInclusive . blockRealPoint
+
+    blockRealPoint blk = case pointToWithOriginRealPoint $ blockPoint blk of
+      At realPoint -> realPoint
+      _            -> error "Should not happen"
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs:167]: Maybe explain why we don't think this should not happen.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs [hunk 4]
```diff
@@ -178,49 +277,58 @@ runModel model topLevelConfig expr
...
-      Left err -> pure $ Left err
-      Right (mChainUpdate, model') -> do
-        put model'
-        pure $ Right mChainUpdate
+      Left err                     -> (Left err, model)
+      Right (mChainUpdate, model') -> (Right mChainUpdate, model')
 
   addBlock blk = do
     model <- get
+    -- The new block should not be from the future
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs:306]: Why not use `withModelContext`?

**Review by dnadales — COMMENTED** [review]
Nice. Looks good, but I left some comments that we might consider addressing.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs (hunk 2 above)
Comment (bartfrenk) [reply ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Unit.hs:148]: There is non-determinism here, since blocks may or may not have been garbage-collected.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 5]
```diff
@@ -600,9 +600,14 @@ iteratorNext itrId blockComponent m =
...
-                     , m { iterators = Map.insert itrId bs (iterators m) }
-                     )
+      Just (b:bs) ->
+        if (blockHash b `Map.member` blocks m)
+        then ( IteratorResult $ getBlockComponent b blockComponent
+             , m { iterators = Map.insert itrId bs (iterators m) }
+             )
+        else ( IteratorBlockGCed $ blockRealPoint b
+             , m { iterators = Map.insert itrId bs (iterators m) }
+             )
```
[the remark this answers is not in the document]
Comment (bartfrenk) [reply ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:610]: Makes sense
