### PR TITLE
Fix: ChainDB QSM test flakyness

### LINKED ISSUE #3389: Fix model/SUT discrepancy in Chain DB tests
# The error 

The model and SUT disagree on the validity of a point. More precisely, the point that corresponds to block with slot 11, block number 5.

For ease of reference, the ultimate error message is this:

```
PostconditionFailed
  "AnnotateC \"real response didn't match model response\" 
  (PredicateC 
    (    Resp {getResp = Right (IsValid (IsValidResult {real = True, isValid = Just True}))}
     :/= Resp {getResp = Right (IsValid (IsValidResult {real = False, isValid = Nothing}))})
  )" /= Ok
```

<details>
  <summary>Click to see the full error message</summary>
  
```
FAIL (135.08s)
          *** Failed! Falsified (after 59650 tests and 12 shrinks):
          MaxClockSkew 100000
          SmallChunkInfo (UniformChunkSize (ChunkSize {chunkCanContainEBB = False, numRegularBlocks = 13}))
          Commands
            { unCommands =
                [ Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-8556510898270155945)
                                    , thPrevHash = GenesisHash
                                    , thBodyHash = TestBodyHash (-7234408896584323076)
                                    , thSlotNo = SlotNo 1
                                    , thBlockNo = BlockNo 0
                                    , thChainLength = ChainLength 1
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 1
                                          , blockPointHash = TestHeaderHash (-8556510898270155945)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-2888999216768647131)
                                    , thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945))
                                    , thBodyHash = TestBodyHash (-7234408896584323076)
                                    , thSlotNo = SlotNo 3
                                    , thBlockNo = BlockNo 1
                                    , thChainLength = ChainLength 2
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 3
                                          , blockPointHash = TestHeaderHash (-2888999216768647131)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 2102088202601657634
                                    , thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131))
                                    , thBodyHash = TestBodyHash (-7234408896601100693)
                                    , thSlotNo = SlotNo 5
                                    , thBlockNo = BlockNo 2
                                    , thChainLength = ChainLength 3
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 2 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 5
                                          , blockPointHash = TestHeaderHash 2102088202601657634
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-8617166116099525105)
                                    , thPrevHash = BlockHash (TestHeaderHash 7412945834010847025)
                                    , thBodyHash = TestBodyHash (-7234408896584323076)
                                    , thSlotNo = SlotNo 11
                                    , thBlockNo = BlockNo 4
                                    , thChainLength = ChainLength 5
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 5
                                          , blockPointHash = TestHeaderHash 2102088202601657634
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 7412945834010847025
                                    , thPrevHash = BlockHash (TestHeaderHash 2102088202601657634)
                                    , thBodyHash = TestBodyHash (-7234408896617878314)
                                    , thSlotNo = SlotNo 8
                                    , thBlockNo = BlockNo 3
                                    , thChainLength = ChainLength 4
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 1 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 11
                                          , blockPointHash = TestHeaderHash (-8617166116099525105)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-8276854694911826380)
                                    , thPrevHash = BlockHash (TestHeaderHash 7412945834010847025)
                                    , thBodyHash = TestBodyHash (-7234408896584323076)
                                    , thSlotNo = SlotNo 10
                                    , thBlockNo = BlockNo 4
                                    , thChainLength = ChainLength 5
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 10
                                          , blockPointHash = TestHeaderHash (-8276854694911826380)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 455202168906668063
                                    , thPrevHash = BlockHash (TestHeaderHash (-8276854694911826380))
                                    , thBodyHash = TestBodyHash (-7234408896601100693)
                                    , thSlotNo = SlotNo 11
                                    , thBlockNo = BlockNo 5
                                    , thChainLength = ChainLength 6
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 2 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 11
                                          , blockPointHash = TestHeaderHash 455202168906668063
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 5691200944682986263
                                    , thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105))
                                    , thBodyHash = TestBodyHash (-7234408896601100693)
                                    , thSlotNo = SlotNo 12
                                    , thBlockNo = BlockNo 5
                                    , thChainLength = ChainLength 6
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 2 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 12
                                          , blockPointHash = TestHeaderHash 5691200944682986263
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-5397328272732179662)
                                    , thPrevHash = BlockHash (TestHeaderHash 5691200944682986263)
                                    , thBodyHash = TestBodyHash (-7234408896584323076)
                                    , thSlotNo = SlotNo 14
                                    , thBlockNo = BlockNo 6
                                    , thChainLength = ChainLength 7
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 14
                                          , blockPointHash = TestHeaderHash (-5397328272732179662)
                                          }))
                            }
                      }
                    []
                , Command
                    At { unAt = PersistBlksThenGC }
                    At { unAt = Resp { getResp = Right (Unit ()) } }
                    []
                , Command
                    At
                      { unAt =
                          GetIsValid
                            (RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063))
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right (IsValid IsValidResult { real = False , isValid = Nothing })
                            }
                      }
                    []
                ]
            }
          Model chain: Genesis :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 2, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 1, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash 5691200944682986263, thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 12, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 2, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash (-5397328272732179662), thPrevHash = BlockHash (TestHeaderHash 5691200944682986263), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 14, thBlockNo = BlockNo 6, thChainLength = ChainLength 7, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}}
          TraceEvents: TraceImmutableDBEvent NoValidLastLocation
          TraceOpenEvent (OpenedImmutableDB Origin 0)
          TraceOpenEvent OpenedVolatileDB
          TraceLedgerReplayEvent (ReplayFromGenesis Origin)
          TraceOpenEvent OpenedLgrDB
          TraceOpenEvent (OpenedDB Origin Origin)
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 1) (TestHeaderHash (-8556510898270155945))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 1) (TestHeaderHash (-8556510898270155945))) (BlockNo 0) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 1) (TestHeaderHash (-8556510898270155945))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 1) (TestHeaderHash (-8556510898270155945)), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 1, newTipTrigger = RealPoint (SlotNo 1) (TestHeaderHash (-8556510898270155945))}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList []}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 3) (TestHeaderHash (-2888999216768647131))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 3) (TestHeaderHash (-2888999216768647131))) (BlockNo 1) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 3) (TestHeaderHash (-2888999216768647131))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 1) (TestHeaderHash (-8556510898270155945)) (BlockNo 0), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 3) (TestHeaderHash (-2888999216768647131)), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 3, newTipTrigger = RealPoint (SlotNo 3) (TestHeaderHash (-2888999216768647131))}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 5) (TestHeaderHash 2102088202601657634)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 5) (TestHeaderHash 2102088202601657634)) (BlockNo 2) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 5) (TestHeaderHash 2102088202601657634)))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 3) (TestHeaderHash (-2888999216768647131)) (BlockNo 1), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 5) (TestHeaderHash 2102088202601657634), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 5, newTipTrigger = RealPoint (SlotNo 5) (TestHeaderHash 2102088202601657634)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 11) (TestHeaderHash (-8617166116099525105))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 11) (TestHeaderHash (-8617166116099525105))) (BlockNo 4) IsNotEBB)
          TraceAddBlockEvent (StoreButDontChange (RealPoint (SlotNo 11) (TestHeaderHash (-8617166116099525105))))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 8) (TestHeaderHash 7412945834010847025)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 8) (TestHeaderHash 7412945834010847025)) (BlockNo 3) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 8) (TestHeaderHash 7412945834010847025)))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 5) (TestHeaderHash 2102088202601657634) (BlockNo 2), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 11) (TestHeaderHash (-8617166116099525105)), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 11, newTipTrigger = RealPoint (SlotNo 8) (TestHeaderHash 7412945834010847025)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 10) (TestHeaderHash (-8276854694911826380))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 10) (TestHeaderHash (-8276854694911826380))) (BlockNo 4) IsNotEBB)
          TraceAddBlockEvent (TrySwitchToAFork (RealPoint (SlotNo 10) (TestHeaderHash (-8276854694911826380))) (ChainDiff {getRollback = 1, getSuffix = AnchoredSeq {anchor = Anchor (SlotNo 8) (TestHeaderHash 7412945834010847025) (BlockNo 3), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 10, headerFieldBlockNo = BlockNo 4, headerFieldHash = TestHeaderHash (-8276854694911826380)}}]}}}))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 8) (TestHeaderHash 7412945834010847025) (BlockNo 3), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8276854694911826380), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 10, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (SwitchedToAFork [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 10) (TestHeaderHash (-8276854694911826380)), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 10, newTipTrigger = RealPoint (SlotNo 10) (TestHeaderHash (-8276854694911826380))}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8276854694911826380), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 10, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063)) (BlockNo 5) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063)))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 10) (TestHeaderHash (-8276854694911826380)) (BlockNo 4), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 455202168906668063, thPrevHash = BlockHash (TestHeaderHash (-8276854694911826380)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 11, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 11, newTipTrigger = RealPoint (SlotNo 11) (TestHeaderHash 455202168906668063)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8276854694911826380), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 10, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8276854694911826380), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 10, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 455202168906668063, thPrevHash = BlockHash (TestHeaderHash (-8276854694911826380)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 11, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 12) (TestHeaderHash 5691200944682986263)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 12) (TestHeaderHash 5691200944682986263)) (BlockNo 5) IsNotEBB)
          TraceAddBlockEvent (TrySwitchToAFork (RealPoint (SlotNo 12) (TestHeaderHash 5691200944682986263)) (ChainDiff {getRollback = 2, getSuffix = AnchoredSeq {anchor = Anchor (SlotNo 8) (TestHeaderHash 7412945834010847025) (BlockNo 3), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 11, headerFieldBlockNo = BlockNo 4, headerFieldHash = TestHeaderHash (-8617166116099525105)}},MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 12, headerFieldBlockNo = BlockNo 5, headerFieldHash = TestHeaderHash 5691200944682986263}}]}}}))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 8) (TestHeaderHash 7412945834010847025) (BlockNo 3), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 5691200944682986263, thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 12, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (SwitchedToAFork [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 12) (TestHeaderHash 5691200944682986263), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 12, newTipTrigger = RealPoint (SlotNo 12) (TestHeaderHash 5691200944682986263)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8276854694911826380), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 10, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 455202168906668063, thPrevHash = BlockHash (TestHeaderHash (-8276854694911826380)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 11, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 5691200944682986263, thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 12, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 14) (TestHeaderHash (-5397328272732179662))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 14) (TestHeaderHash (-5397328272732179662))) (BlockNo 6) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 14) (TestHeaderHash (-5397328272732179662))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 12) (TestHeaderHash 5691200944682986263) (BlockNo 5), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-5397328272732179662), thPrevHash = BlockHash (TestHeaderHash 5691200944682986263), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 14, thBlockNo = BlockNo 6, thChainLength = ChainLength 7, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 14) (TestHeaderHash (-5397328272732179662)), newTipEpoch = EpochNo 1, newTipSlotInEpoch = 1, newTipTrigger = RealPoint (SlotNo 14) (TestHeaderHash (-5397328272732179662))}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 5691200944682986263, thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 12, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8556510898270155945), thPrevHash = GenesisHash, thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 1, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2888999216768647131), thPrevHash = BlockHash (TestHeaderHash (-8556510898270155945)), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 3, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2102088202601657634, thPrevHash = BlockHash (TestHeaderHash (-2888999216768647131)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 5, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 7412945834010847025, thPrevHash = BlockHash (TestHeaderHash 2102088202601657634), thBodyHash = TestBodyHash (-7234408896617878314), thSlotNo = SlotNo 8, thBlockNo = BlockNo 3, thChainLength = ChainLength 4, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-8617166116099525105), thPrevHash = BlockHash (TestHeaderHash 7412945834010847025), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 11, thBlockNo = BlockNo 4, thChainLength = ChainLength 5, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 5691200944682986263, thPrevHash = BlockHash (TestHeaderHash (-8617166116099525105)), thBodyHash = TestBodyHash (-7234408896601100693), thSlotNo = SlotNo 12, thBlockNo = BlockNo 5, thChainLength = ChainLength 6, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-5397328272732179662), thPrevHash = BlockHash (TestHeaderHash 5691200944682986263), thBodyHash = TestBodyHash (-7234408896584323076), thSlotNo = SlotNo 14, thBlockNo = BlockNo 6, thChainLength = ChainLength 7, thIsEBB = RegularBlock}}]}}))
          TraceCopyToImmutableDBEvent (CopiedBlockToImmutableDB (At (Block {blockPointSlot = SlotNo 1, blockPointHash = TestHeaderHash (-8556510898270155945)})))
          TraceCopyToImmutableDBEvent (CopiedBlockToImmutableDB (At (Block {blockPointSlot = SlotNo 3, blockPointHash = TestHeaderHash (-2888999216768647131)})))
          TraceCopyToImmutableDBEvent (CopiedBlockToImmutableDB (At (Block {blockPointSlot = SlotNo 5, blockPointHash = TestHeaderHash 2102088202601657634})))
          TraceCopyToImmutableDBEvent (CopiedBlockToImmutableDB (At (Block {blockPointSlot = SlotNo 8, blockPointHash = TestHeaderHash 7412945834010847025})))
          TraceCopyToImmutableDBEvent (CopiedBlockToImmutableDB (At (Block {blockPointSlot = SlotNo 11, blockPointHash = TestHeaderHash (-8617166116099525105)})))
          TraceGCEvent (PerformedGC (SlotNo 11))


          PostconditionFailed "AnnotateC \"real response didn't match model response\" (PredicateC (Resp {getResp = Right (IsValid (IsValidResult {real = True, isValid = Just True}))} :/= Resp {getResp = Right (IsValid (IsValidResult {real = False, isValid = Nothing}))}))" /= Ok
          Use --quickcheck-replay=999301 to reproduce.

```

</details>

The error can be reproduced running:

```sh
cabal new-run test-storage -- -p "ChainDB q-s-m" --quickcheck-replay 999301
```

## Counterexample actions

    - Block (-8556510898270155945) (s 1)  (b 0) (<-  GenesisHash        )
    - Block (-2888999216768647131) (s 3)  (b 1) (<- -8556510898270155945)
    - Block (2102088202601657634)  (s 5)  (b 2) (<- -2888999216768647131)
    - Block (-8617166116099525105) (s 11) (b 4) (<-  7412945834010847025)
    - Block (7412945834010847025)  (s 8)  (b 3) (<-  2102088202601657634)
    - Block (-8276854694911826380) (s 10) (b 4) (<-  7412945834010847025)
    - Block (455202168906668063)   (s 11) (b 5) (<- -8276854694911826380)
    - Block (5691200944682986263)  (s 12) (b 5) (<- -8617166116099525105)
    - Block (-5397328272732179662) (s 14) (b 6) (<-  5691200944682986263)

Adding these blocks would result in this chain:

# What might be going wrong

The SUT considers the point that corresponds to block `s 11, b 5` as valid,
whereas the model does not have information about its validity.

The model reports that it does not know about the validity of point that
corresponds to block:

-   Block (455202168906668063)   (s 11) (b 5) (<- -8276854694911826380)

i.e., it returns `Nothing`. Why?

-   [Valid points according](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L324) to the model are those that can form [valid](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L624) chains
    that [start from genesis](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L737) with the blocks [from the immutable DB and the
    volatile DB](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L166).
-   We garbage collect blocks smaller than slot 11 (we can see this in
    the logs, and infer this from the fact that the last seen slot when we
    call GC is `14` and `k=2`, so block `s 11, b 4` is at the tip of the
    immutable DB).
-   When [we garbage collect](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L940) blocks smaller than slot 11, block `s 10, b 4`
    gets removed from the volatile DB because its [slot number is smaller than
    slot number of the immutable tip](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs#L900).
-   As a result, we cannot construct a path from genesis to block `s 11, b 5`
    using blocks in the volatile DB and immutable DB because its predecessor
    was removed from the volatile DB.
-   Thus the model reports that the validity of the point that corresponds to
    block at  `s 11, b 5` is unknown (it returns `Nothing`).

The SUT considers the point as valid because block `s 11, b 5` is still in
the volatile DB after garbage collection.

Based on this analysis, I'd conclude that the [comment about
`IsValidResult`](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs#L495) is wrong: the model does not know about all valid blocks.

I do not know how we want to fix this. Edsko seems to prefer weakening the
equality instance of `IsValidResult` so that it returns `True` when either
the SUT or the model return `Nothing`.

I am worried that the SUT and model definitions of `getIsValid` do not
match. I'd argue that in this case both the model and the SUT know that the
point that corresponds to `s 11, b 5` is valid.

# Additional questions

- Why did the tests not catch this before?
- Why can't QC shrink the counterexample further?

### LINKED ISSUE #3440: Triage another ChainDB q-s-m sequential failure
https://hydra.iohk.io/build/7995771/nixlog/1

`Use --quickcheck-replay=758015 to reproduce.`

https://hydra.iohk.io/build/7995771

commit https://hydra.iohk.io/build/7995771

### PR DESCRIPTION
**Pull request by Jasagredo**
ChainDB QSM didn't have a notion of validity for blocks that were in
chain suffixes no longer connected to the Genesis block. It now carries
a Set of known-valid blocks to answer the `GetIsValid` query.

Closes CAD-4002
Closes CAD-3590
Closes CAD-3601
Closes #3389
Closes #3440

### CODE REVIEW

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 1]
```diff
@@ -313,28 +314,20 @@ immutableSlotNo :: HasHeader blk
...
-    | otherwise                   -> Nothing
-  where
-    validPoints :: Set (RealPoint blk)
-    validPoints =
-          foldMap (Set.fromList . map blockRealPoint . Chain.toOldestFirst . fst)
-        . snd
-        . validChains cfg m
-        . blocks
-        $ m
+getIsValid m = \(RealPoint _ hash) -> if
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:319]: This looks much simpler :ok_hand:

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 2]
```diff
@@ -446,18 +444,33 @@ addBlock cfg blk m = Model {
...
           (selectView (configBlock cfg) . getHeader)
           (currentChain m)
-      . filter (extendsImmutableChain . fst)
-      $ candidates
+      $ consideredCandidates
 
-addBlocks :: LedgerSupportsProtocol blk
+    -- Sometimes blocks are added not in order and therefore we cannot just look
+    -- at the last added block and push it to the set of known valid blocks. The
+    -- easiest (and considering the lengths of the generated chains) way is to
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:451]: Maybe we can reword the sentence between parentheses (it's a bit long and breaks the continuity)

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 3]
```diff
@@ -621,6 +634,7 @@ class ( HasHeader blk
 -------------------------------------------------------------------------------}
 
 type InvalidBlocks blk = Map (HeaderHash blk) (InvalidBlockReason blk, SlotNo)
+type ValidBlocks blk = Set (HeaderHash blk)
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:637]: As far as I can see we use `ValidBlocks` only once. Would it make sense to remove the extra level of indirection?

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 4]
```diff
@@ -446,18 +444,33 @@ addBlock cfg blk m = Model {
...
+    -- Also, the chain selection algorithm in the SUT will test chains one by
+    -- one until it finds the one that should be selected, so prefixes of chains
+    -- will be tested for validity and blocks in those prefixes might be
+    -- included in the set of known valid blocks. Therefore, as we know which
+    -- chain was selected, and on every chain we know the valid blocks, we will
+    -- fold over the candidates up to (and including) the selected one.
+    valid' = foldl
+               (Chain.foldChain (\s b -> Set.insert (blockHash b) s))
+               (valid m)
+               (takeWhile (not . Chain.isPrefixOf newChain) (map fst consideredCandidates) ++ [newChain])
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:463]: Why do we need the `newChain` here? Shouldn't it be part of `consideredCandidates`

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 5]
```diff
@@ -446,18 +444,33 @@ addBlock cfg blk m = Model {
...
-      $ candidates
+      $ consideredCandidates
 
-addBlocks :: LedgerSupportsProtocol blk
+    -- Sometimes blocks are added not in order and therefore we cannot just look
+    -- at the last added block and push it to the set of known valid blocks. The
+    -- easiest (and considering the lengths of the generated chains) way is to
+    -- just push all the valid blocks in the chain into the set.
+    --
+    -- Also, the chain selection algorithm in the SUT will test chains one by
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:454]: I don't know if we should be referring to the SUT behaviour here. I wonder if we could omit the SUT part.

**Review by dnadales — APPROVED** [review]

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs (hunk 4 above)
Comment (dnadales) [reply ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:463]: Discussed with Javier: it took us >1 hour to convince ourselves that this correctly reflected the behaviour of the chain selection algorithm regarding the addition of valid blocks upon chain selection. So we should add some additional clarifications. Motivating example:

```
consideredCandidates

C0: vvvvxxxxxx
C1: vvvvvvx
C2: vvv

```

```
selectChain:

C1: vvvvvvx
C0: vvvvxxxxxx
C2: vvv

```

```
newChain: C1
```

Therefore:

```
new valid blocks: v's of C0 + v's of C1
```

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 6]
```diff
@@ -446,22 +446,109 @@ addBlock cfg blk m = Model {
...
+--    >                            = listToMaybe ([C1V, C0V, C2])
+--    >                            = Just C1V
+--
+--    The selected candidate will be the same one that the chain selection
+--    algorithm would choose. However, as the chain selection algorithm will
+--    consider the candidates as they were sorted by 'SelectView' on the
+--    non-truncated candidates, blcoks in 'C0v' are also known to be valid by
+--    the real algorithm.
+--
+--    To achieve this, we can process the list of candidates returned by
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:539]: Sorry, to achieve what exactly? :D 

Also "we" = the model's CS algorithm?

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 7]
```diff
@@ -446,22 +446,109 @@ addBlock cfg blk m = Model {
...
+--    'validChains' until we find the one 'selectChain' selected as these will be
+--    the ones that the real algorithm would test and re-add to the list once
+--    truncated.
+--
+--    > knownInvalid = append (C0I + C1I) knownInvalid
+--    > knownValid   = foldl append knownValid (takeWhile (/= C1V) candidates ++ [C1V])
+--
+--    Note that the set of known valid blocks is equivalent to the set on the
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:547]:
```suggestion
--    Note that the set of known valid blocks is equivalent to the set computed by
```

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 8]
```diff
@@ -446,22 +446,109 @@ addBlock cfg blk m = Model {
...
+--    >                            = Just C1V
+--
+--    The selected candidate will be the same one that the chain selection
+--    algorithm would choose. However, as the chain selection algorithm will
+--    consider the candidates as they were sorted by 'SelectView' on the
+--    non-truncated candidates, blcoks in 'C0v' are also known to be valid by
+--    the real algorithm.
+--
+--    To achieve this, we can process the list of candidates returned by
+--    'validChains' until we find the one 'selectChain' selected as these will be
```
Comment (dnadales) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:540]: I'm having trouble trying to understand what we want to explain here.

**Review by dnadales — COMMENTED** [review]
Thanks for adding this nice explanation Javier. Let's go over my comments on a call, and if @nfrisby does not object we can merge this.

**Comment by Jasagredo** [comment]
bors retry
