### PR TITLE
Fix EBB-related bugs

### LINKED ISSUE #1339: Bug in ChainDB.Reader
While working on #966 (see this branch https://github.com/input-output-hk/ouroboros-network/tree/nfrisby/issue-966-more-EBBs), @nfrisby found a bug in the ChainDB.Readers.

I'll quote @nfrisby:

```
145	FailureException ExceptionInLinkedThread "ThreadId 3" (MiniProtocolFatalException {mpfeType = ImmutableDBError, mpfeExn = ReadFutureSlotError (requested was SlotNo {unSlotNo = 0}, tip is TipGen): CallStack (from HasCallStack):
146	  throwUserError, called at src/Ouroboros/Storage/ImmutableDB/Impl/Util.hs:146:9 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ImmutableDB.Impl.Util
147	  validateIteratorRange, called at src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs:130:14 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ImmutableDB.Impl.Iterator
148	  streamImpl, called at src/Ouroboros/Storage/ImmutableDB/Impl.hs:213:24 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ImmutableDB.Impl
149	  streamBlocks_, called at src/Ouroboros/Storage/ImmutableDB/API.hs:211:5 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ImmutableDB.API
150	  streamBlocks, called at src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs:395:37 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.ImmDB
151	  registeredStream, called at src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs:484:5 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.ImmDB
152	  streamBlocksAfter, called at src/Ouroboros/Storage/ChainDB/Impl/Reader.hs:286:15 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.Reader
153	  instructionHelper, called at src/Ouroboros/Storage/ChainDB/Impl/Reader.hs:175:57 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.Reader
154	  makeNewBlockOrHeaderReader, called at src/Ouroboros/Storage/ChainDB/Impl/Reader.hs:102:18 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.Reader
155	  newReader, called at src/Ouroboros/Storage/ChainDB/Impl/Reader.hs:120:30 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl.Reader
156	  newHeaderReader, called at src/Ouroboros/Storage/ChainDB/Impl.hs:169:34 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.Impl
157	  newHeaderReader_, called at src/Ouroboros/Storage/ChainDB/API.hs:250:7 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Storage.ChainDB.API
158	  newHeaderReader, called at src/Ouroboros/Consensus/ChainSyncServer.hs:42:14 in ouroboros-consensus-0.1.0.0-inplace:Ouroboros.Consensus.ChainSyncServer, mpfeClient = CoreNodeId 1, mpfeServer = CoreNodeId 0})
```

Here's what's happening:
```
-- slot 0: 0 forges EBB and B1
-- slot 1: 1 forges EBB and B1'; 2 adopts B1 but 0 stubbornly retains B1
-- slot 2: 2 forges B2 atop B1', 1 adopts B2, and then 0 capitulates and switches from B1 to B1' so it can also adopt B2. Then crash.
let f i mbI = (CoreNodeId i, maybe Set.empty (Set.singleton . CoreNodeId) mbI) in
prop_simple_real_pbft_convergence
  TestConfig
    { numCoreNodes = NumCoreNodes 3
    , numSlots     = NumSlots 3
    , nodeJoinPlan = NodeJoinPlan (Map.fromList [ (CoreNodeId i, s) | (i, s) <- [(0, 0), (1, 1), (2, 1)] ])
      -- 0 <-> 1 <-> 2
    , nodeTopology = NodeTopology (Map.fromList [f 0 Nothing, f 1 (Just 0), f 2 (Just 1)])
    }
  Seed {getSeed = (8649794079670178548,11766432898991644479,7324597640402777313,6172196011705614009,2712292517831002552)}
```

It doesn't crash if I change the topology to be mesh, but I don't know why not yet.

The exception is being incurred by node 0's (only) ChainSync server (which is peered with node 1). Node 0's trace includes this during slot 2

```
SwitchedToChain
  { _prevChain = AnchoredFragment {anchorPoint = Origin, unanchorFragment = ChainFragment (SFT (fromList
[ABOBBoundaryHdr AbstractHash 3c2a8234e7b7b68b749b9ffd2a5ca4b8dbd97d4ae08285524f109abaa967f980}}
,ABOBBlockHdr AbstractHash 6d0c191128571adf009ecb5b8c60834afe6713f7bf4fdd0b5edb57082718a1c6}}
]))}
  , _newChain = AnchoredFragment {anchorPoint = Origin, unanchorFragment = ChainFragment (SFT (fromList
[ABOBBoundaryHdr AbstractHash 3c2a8234e7b7b68b749b9ffd2a5ca4b8dbd97d4ae08285524f109abaa967f980}}
,ABOBBlockHdr AbstractHash 0841a09dc5cff315a665afc78abadd344f5d6164c271dda3b282e9c23072c39a}}
,ABOBBlockHdr AbstractHash 750563dc75ed80df2f8dbbafa4e125346ab3b8606fe6d6e6affd66271d4e233a}}
]))}
ReaderNoLongerInMem (RollForwardFrom (At (Block {blockPointSlot = SlotNo {unSlotNo = 0}, blockPointHash = ByronHash {unByronHash = AbstractHash 6d0c191128571adf009ecb5b8c60834afe6713f7bf4fdd0b5edb57082718a1c6}})))
```
before the crash.

6d0c1911 is the proper block that node 0 forged in slot 0
0841a09d is the proper block that node 1 forged in slot 1
750563dc is the proper block that node 2 forged in slot 2

So it seems like the Reader is somehow stale. It was dormant (CS server has sent MsgAwaitReply) until that chain switch woke it up.

Maybe the logic for a stale reader is a little off when the switch rolls all the way back to the Epoch 0 EBB?

### PR DESCRIPTION
**Pull request by mrBliss**
Closes #1339.

After fixing the bug, I investigated why the ChainDB quickcheck-state-machine tests hadn't triggered it before. I discovered that no regular blocks in the same slot as an EBB were being generated. After fixing that, I discovered a few more EBB-related bugs.

To fix one of them, I pulled in parts of #1323 (which I will rebase after this branch is merged): a92f3f4 and 19fd306.

### CODE REVIEW

**Comment by mrBliss** [comment]
I ran 1,000,000 tests ChainDB q-s-m and they passed.

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs [hunk 1]
```diff
@@ -1099,7 +1099,9 @@ genBlk Model{..} = frequency
     genFitsOn b = frequency
         -- If we generate too many EBBs, the density of the chain will be low.
```
Comment (nfrisby) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs]: Is this comment now stale?

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ImmutableDB/Model.hs [hunk 2]
```diff
@@ -450,7 +457,10 @@ getEBBBinaryInfo :: (HasCallStack, MonadState (DBModel hash) m)
 getEBBBinaryInfo err epoch = do
     dbm@DBModel {..} <- get
     let currentEpoch = dbmCurrentEpoch dbm
-        inTheFuture  = epoch > currentEpoch || dbmTip == TipGen
+        inTheFuture  = epoch > currentEpoch ||
+          case dbmTip of
+            TipGen -> True
+            Tip _  -> False
```
Comment (nfrisby) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ImmutableDB/Model.hs]: Mostly curiosity: What's the motivation for this change?

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs (hunk 1 above)
Comment (mrBliss) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs]: Good point.

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ImmutableDB/Model.hs (hunk 2 above)
Comment (mrBliss) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ImmutableDB/Model.hs]: As a prerequisite for 19fd30620de8dc134bbbba74fb4b880467c72ab6, we now track the hash of the block/ebb in the `Tip` (both in the impl and the model), so `dbmTip == TipGen` would require `Eq hash`, hence the simple pattern-match.
