### PR TITLE
Improve model ChainSel to fix ChainDB QSM test flakiness

### LINKED ISSUE #3689: ChainDB q-s-m failure with `GetIsValid`
### To reproduce

Run 
```
cabal run test-storage -- -p 'ChainDB q-s-m' --quickcheck-replay=455411
```
on fa10cb4eef1e7d3e095cec3c2bb1210774b7e5fa (master at time of writing). This yields
```
(PredicateC (Resp {getResp = Right (IsValid (IsValidResult {real = True, isValid = Just True}))}

:/=          Resp {getResp = Right (IsValid (IsValidResult {real = False, isValid = Nothing}))}))
```

This is exactly what #3651 ought to have fixed.

(edit NSF: just an update: it also fails on today's `master` tip, 03f935ec6, if you revert PR 3743, which disables this aspect of the test, before running with that seed)

### Cursory glance

The QSM commands look like this:
```
 - Add valid   block Genesis >: A with hash 2173152789646624309
 - Add valid   block A       >: B with hash 9122512639099877219
 - Add valid   block B       >: C with hash -7915818155603348863
 - Add invalid block C       >: D with hash -1393368485677491682
 - Add valid   block A       >: E with hash -2651776708921877814
 - Add invalid block E       >: F with hash 128720366063791916
 - Check if E is valid
    - ChainSel says: yes, valid
    - Model says:    unknown

Chain tree:
  Genesis >: A >: B >: C  :> D*
                  ∧    ∧
               >: E >: F*
* invalid
```

My interpretation: The model is wrong here, we have to validate `E` as the chain diff with rollback 2 and fragment `E >: F` is an improvement over our currently selected chain `A >: B >: C` as `C < F`. So even though we end up not selecting it as `F` is invalid, ChainSel still learns that `E` is valid.

We already have some asymmetry when comparing these validity results:

https://github.com/input-output-hk/ouroboros-network/blob/fa10cb4eef1e7d3e095cec3c2bb1210774b7e5fa/ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs#L501-L504

Concretely, it is for the "other way around": when ChainSel does not know whether a block is valid, we intentionally don't check whether the model agrees.

### Full log

<details>
<summary>Click to expand</summary>

```
      ChainDB q-s-m
        sequential:
Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [],
    immutableDbChain = Genesis,
    cps = ChainProducerState {
      chainState = Genesis,
      chainFollowers = Map.fromList
        [],
      nextFollowerId = 0},
    currentLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point Origin,
        lastAppliedHash = GenesisHash},
      headerState = HeaderState {
        headerStateTip = Origin,
        headerStateChainDep = `()`}},
    initLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point Origin,
        lastAppliedHash = GenesisHash},
      headerState = HeaderState {
        headerStateTip = Origin,
        headerStateChainDep = `()`}},
    iterators = Map.fromList [],
    valid = Set.fromList [],
    invalid = Map.fromList [],
    currentSlot = SlotNo 0,
    maxClockSkew = 100000,
    isOpen = True},
  knownIters = RefEnv [],
  knownFollowers = RefEnv [],
  modelConfig = Opaque}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash 2173152789646624309
                , thPrevHash = GenesisHash
                , thBodyHash = TestBodyHash 590680769285548757
                , thSlotNo = SlotNo 0
                , thBlockNo = BlockNo 0
                , thChainLength = ChainLength 1
                , thIsEBB = EBB (EpochNo 0)
                }
          , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 0
                      , blockPointHash = TestHeaderHash 2173152789646624309
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        +_×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    cps = ChainProducerState {
      chainState = -Genesis
      +:>
        Genesis
        TestBlock {
          testHeader = TestHeader {
            thHash = TestHeaderHash
              2173152789646624309,
            thPrevHash = GenesisHash,
            thBodyHash = TestBodyHash
              590680769285548757,
            thSlotNo = SlotNo 0,
            thBlockNo = BlockNo 0,
            thChainLength = ChainLength 1,
            thIsEBB = EBB (EpochNo 0)},
          testBody = TestBody {
            tbForkNo = 3,
            tbIsValid = True}},
      nextFollowerId = 0,
      chainFollowers = ...},
    currentLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point
          -Origin
          +(At
            Block {
              blockPointSlot = SlotNo 0,
              blockPointHash = TestHeaderHash
                2173152789646624309}),
        lastAppliedHash = -GenesisHash
        +BlockHash
          (TestHeaderHash
            2173152789646624309)},
      headerState = HeaderState {
        headerStateTip = -Origin
        +At
          AnnTip {
            annTipSlotNo = SlotNo 0,
            annTipBlockNo = BlockNo 0,
            annTipInfo = TipInfoIsEBB
              (TestHeaderHash
                2173152789646624309)
              IsEBB},
        headerStateChainDep = `()`}},
    valid = Set.fromList
      [
        +TestHeaderHash
          2173152789646624309],
    maxClockSkew = 100000,
    isOpen = True,
    initLedger = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash 9122512639099877219
                , thPrevHash = BlockHash (TestHeaderHash 2173152789646624309)
                , thBodyHash = TestBodyHash 590681868797176966
                , thSlotNo = SlotNo 0
                , thBlockNo = BlockNo 1
                , thChainLength = ChainLength 2
                , thIsEBB = RegularBlock
                }
          , testBody = TestBody { tbForkNo = 2 , tbIsValid = True }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 0
                      , blockPointHash = TestHeaderHash 9122512639099877219
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        +_×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    cps = ChainProducerState {
      chainState = :>
        -Genesis
        +(:>
          Genesis
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}})
        TestBlock {
          testHeader = TestHeader {
            thHash = TestHeaderHash
              -2173152789646624309
              +9122512639099877219,
            thPrevHash = -GenesisHash
            +BlockHash
              (TestHeaderHash
                2173152789646624309),
            thBodyHash = TestBodyHash
              -590680769285548757
              +590681868797176966,
            thBlockNo = BlockNo -0 +1,
            thChainLength = ChainLength
              -1
              +2,
            thIsEBB = -EBB (EpochNo 0)
            +RegularBlock,
            thSlotNo = ...},
          testBody = TestBody {
            tbForkNo = -3 +2,
            tbIsValid = True}},
      nextFollowerId = 0,
      chainFollowers = ...},
    currentLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point
          (At
            Block {
              blockPointHash = TestHeaderHash
                -2173152789646624309
                +9122512639099877219,
              blockPointSlot = ...}),
        lastAppliedHash = BlockHash
          (TestHeaderHash
            -2173152789646624309
            +9122512639099877219)},
      headerState = HeaderState {
        headerStateTip = At
          AnnTip {
            annTipBlockNo = BlockNo -0 +1,
            annTipInfo = TipInfoIsEBB
              (TestHeaderHash
                -2173152789646624309
                +9122512639099877219)
              -IsEBB
              +IsNotEBB,
            annTipSlotNo = ...},
        headerStateChainDep = `()`}},
    valid = Set.fromList
      [
        TestHeaderHash
          2173152789646624309,
        +TestHeaderHash
          9122512639099877219],
    maxClockSkew = 100000,
    isOpen = True,
    initLedger = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash (-7915818155603348863)
                , thPrevHash = BlockHash (TestHeaderHash 9122512639099877219)
                , thBodyHash = TestBodyHash 590680769285548757
                , thSlotNo = SlotNo 1
                , thBlockNo = BlockNo 2
                , thChainLength = ChainLength 3
                , thIsEBB = RegularBlock
                }
          , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 1
                      , blockPointHash = TestHeaderHash (-7915818155603348863)
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        +_×_
          (TestHeaderHash
            `-7915818155603348863`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-7915818155603348863`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  9122512639099877219),
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 1,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    cps = ChainProducerState {
      chainState = :>
        (:>
          -Genesis
          +(:>
            Genesis
            TestBlock {
              testHeader = TestHeader {
                thHash = TestHeaderHash
                  2173152789646624309,
                thPrevHash = GenesisHash,
                thBodyHash = TestBodyHash
                  590680769285548757,
                thSlotNo = SlotNo 0,
                thBlockNo = BlockNo 0,
                thChainLength = ChainLength 1,
                thIsEBB = EBB (EpochNo 0)},
              testBody = TestBody {
                tbForkNo = 3,
                tbIsValid = True}})
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                -2173152789646624309
                +9122512639099877219,
              thPrevHash = -GenesisHash
              +BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                -590680769285548757
                +590681868797176966,
              thBlockNo = BlockNo -0 +1,
              thChainLength = ChainLength
                -1
                +2,
              thIsEBB = -EBB (EpochNo 0)
              +RegularBlock,
              thSlotNo = ...},
            testBody = TestBody {
              tbForkNo = -3 +2,
              tbIsValid = True}})
        TestBlock {
          testHeader = TestHeader {
            thHash = TestHeaderHash
              -9122512639099877219
              +`-7915818155603348863`,
            thPrevHash = BlockHash
              (TestHeaderHash
                -2173152789646624309
                +9122512639099877219),
            thBodyHash = TestBodyHash
              -590681868797176966
              +590680769285548757,
            thSlotNo = SlotNo -0 +1,
            thBlockNo = BlockNo -1 +2,
            thChainLength = ChainLength
              -2
              +3,
            thIsEBB = RegularBlock},
          testBody = TestBody {
            tbForkNo = -2 +3,
            tbIsValid = True}},
      nextFollowerId = 0,
      chainFollowers = ...},
    currentLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point
          (At
            Block {
              blockPointSlot = SlotNo -0 +1,
              blockPointHash = TestHeaderHash
                -9122512639099877219
                +`-7915818155603348863`}),
        lastAppliedHash = BlockHash
          (TestHeaderHash
            -9122512639099877219
            +`-7915818155603348863`)},
      headerState = HeaderState {
        headerStateTip = At
          AnnTip {
            annTipSlotNo = SlotNo -0 +1,
            annTipBlockNo = BlockNo -1 +2,
            annTipInfo = TipInfoIsEBB
              (TestHeaderHash
                -9122512639099877219
                +`-7915818155603348863`)
              IsNotEBB},
        headerStateChainDep = `()`}},
    valid = Set.fromList
      [
        +TestHeaderHash
          `-7915818155603348863`,
        TestHeaderHash
          2173152789646624309,
        TestHeaderHash
          9122512639099877219],
    currentSlot = SlotNo -0 +1,
    maxClockSkew = 100000,
    isOpen = True,
    initLedger = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash (-1393368485677491682)
                , thPrevHash = BlockHash (TestHeaderHash (-7915818155603348863))
                , thBodyHash = TestBodyHash 590682968308805178
                , thSlotNo = SlotNo 3
                , thBlockNo = BlockNo 3
                , thChainLength = ChainLength 4
                , thIsEBB = RegularBlock
                }
          , testBody = TestBody { tbForkNo = 1 , tbIsValid = False }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 1
                      , blockPointHash = TestHeaderHash (-7915818155603348863)
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-7915818155603348863`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-7915818155603348863`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  9122512639099877219),
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 1,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        +_×_
          (TestHeaderHash
            `-1393368485677491682`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-1393368485677491682`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-7915818155603348863`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 3,
              thBlockNo = BlockNo 3,
              thChainLength = ChainLength 4,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    invalid = Map.fromList
      [
        +_×_
          (TestHeaderHash
            `-1393368485677491682`)
          (_×_
            (ValidationError
              (ExtValidationErrorLedger
                InvalidBlock))
            (SlotNo 3))],
    currentSlot = SlotNo -1 +3,
    maxClockSkew = 100000,
    isOpen = True,
    cps = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash (-2651776708921877814)
                , thPrevHash = BlockHash (TestHeaderHash 2173152789646624309)
                , thBodyHash = TestBodyHash 590682968308805179
                , thSlotNo = SlotNo 0
                , thBlockNo = BlockNo 1
                , thChainLength = ChainLength 2
                , thIsEBB = RegularBlock
                }
          , testBody = TestBody { tbForkNo = 1 , tbIsValid = True }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 1
                      , blockPointHash = TestHeaderHash (-7915818155603348863)
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-7915818155603348863`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-7915818155603348863`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  9122512639099877219),
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 1,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        +_×_
          (TestHeaderHash
            `-2651776708921877814`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-2651776708921877814`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590682968308805179,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            `-1393368485677491682`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-1393368485677491682`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-7915818155603348863`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 3,
              thBlockNo = BlockNo 3,
              thChainLength = ChainLength 4,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    maxClockSkew = 100000,
    isOpen = True,
    cps = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      AddBlock
        TestBlock
          { testHeader =
              TestHeader
                { thHash = TestHeaderHash 128720366063791916
                , thPrevHash = BlockHash (TestHeaderHash (-2651776708921877814))
                , thBodyHash = TestBodyHash 590682968308805178
                , thSlotNo = SlotNo 2
                , thBlockNo = BlockNo 2
                , thChainLength = ChainLength 3
                , thIsEBB = RegularBlock
                }
          , testBody = TestBody { tbForkNo = 1 , tbIsValid = False }
          }
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right
              (Point
                 (At
                    Block
                      { blockPointSlot = SlotNo 1
                      , blockPointHash = TestHeaderHash (-7915818155603348863)
                      }))
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-7915818155603348863`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-7915818155603348863`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  9122512639099877219),
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 1,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            `-2651776708921877814`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-2651776708921877814`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590682968308805179,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            `-1393368485677491682`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-1393368485677491682`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-7915818155603348863`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 3,
              thBlockNo = BlockNo 3,
              thChainLength = ChainLength 4,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        +_×_
          (TestHeaderHash
            128720366063791916)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                128720366063791916,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-2651776708921877814`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 2,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    invalid = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-1393368485677491682`)
          (_×_
            (ValidationError
              (ExtValidationErrorLedger
                InvalidBlock))
            (SlotNo 3)),
        +_×_
          (TestHeaderHash
            128720366063791916)
          (_×_
            (ValidationError
              (ExtValidationErrorLedger
                InvalidBlock))
            (SlotNo 2))],
    maxClockSkew = 100000,
    isOpen = True,
    cps = ...},
  modelConfig = Opaque,
  knownIters = ...}

   == At
  { unAt =
      GetIsValid
        (RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814)))
  } ==> At
  { unAt =
      Resp
        { getResp =
            Right (IsValid IsValidResult { real = True , isValid = Just True })
        }
  } [ 0 ]

Model {
  dbModel = Model {
    volatileDbBlocks = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-7915818155603348863`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-7915818155603348863`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  9122512639099877219),
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 1,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            `-2651776708921877814`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-2651776708921877814`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590682968308805179,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            `-1393368485677491682`)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                `-1393368485677491682`,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-7915818155603348863`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 3,
              thBlockNo = BlockNo 3,
              thChainLength = ChainLength 4,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        _×_
          (TestHeaderHash
            128720366063791916)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                128720366063791916,
              thPrevHash = BlockHash
                (TestHeaderHash
                  `-2651776708921877814`),
              thBodyHash = TestBodyHash
                590682968308805178,
              thSlotNo = SlotNo 2,
              thBlockNo = BlockNo 2,
              thChainLength = ChainLength 3,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 1,
              tbIsValid = False}},
        _×_
          (TestHeaderHash
            2173152789646624309)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                2173152789646624309,
              thPrevHash = GenesisHash,
              thBodyHash = TestBodyHash
                590680769285548757,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 0,
              thChainLength = ChainLength 1,
              thIsEBB = EBB (EpochNo 0)},
            testBody = TestBody {
              tbForkNo = 3,
              tbIsValid = True}},
        _×_
          (TestHeaderHash
            9122512639099877219)
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}}],
    immutableDbChain = Genesis,
    cps = ChainProducerState {
      chainState = :>
        (:>
          (:>
            Genesis
            TestBlock {
              testHeader = TestHeader {
                thHash = TestHeaderHash
                  2173152789646624309,
                thPrevHash = GenesisHash,
                thBodyHash = TestBodyHash
                  590680769285548757,
                thSlotNo = SlotNo 0,
                thBlockNo = BlockNo 0,
                thChainLength = ChainLength 1,
                thIsEBB = EBB (EpochNo 0)},
              testBody = TestBody {
                tbForkNo = 3,
                tbIsValid = True}})
          TestBlock {
            testHeader = TestHeader {
              thHash = TestHeaderHash
                9122512639099877219,
              thPrevHash = BlockHash
                (TestHeaderHash
                  2173152789646624309),
              thBodyHash = TestBodyHash
                590681868797176966,
              thSlotNo = SlotNo 0,
              thBlockNo = BlockNo 1,
              thChainLength = ChainLength 2,
              thIsEBB = RegularBlock},
            testBody = TestBody {
              tbForkNo = 2,
              tbIsValid = True}})
        TestBlock {
          testHeader = TestHeader {
            thHash = TestHeaderHash
              `-7915818155603348863`,
            thPrevHash = BlockHash
              (TestHeaderHash
                9122512639099877219),
            thBodyHash = TestBodyHash
              590680769285548757,
            thSlotNo = SlotNo 1,
            thBlockNo = BlockNo 2,
            thChainLength = ChainLength 3,
            thIsEBB = RegularBlock},
          testBody = TestBody {
            tbForkNo = 3,
            tbIsValid = True}},
      chainFollowers = Map.fromList
        [],
      nextFollowerId = 0},
    currentLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point
          (At
            Block {
              blockPointSlot = SlotNo 1,
              blockPointHash = TestHeaderHash
                `-7915818155603348863`}),
        lastAppliedHash = BlockHash
          (TestHeaderHash
            `-7915818155603348863`)},
      headerState = HeaderState {
        headerStateTip = At
          AnnTip {
            annTipSlotNo = SlotNo 1,
            annTipBlockNo = BlockNo 2,
            annTipInfo = TipInfoIsEBB
              (TestHeaderHash
                `-7915818155603348863`)
              IsNotEBB},
        headerStateChainDep = `()`}},
    initLedger = ExtLedgerState {
      ledgerState = TestLedger {
        lastAppliedPoint = Point Origin,
        lastAppliedHash = GenesisHash},
      headerState = HeaderState {
        headerStateTip = Origin,
        headerStateChainDep = `()`}},
    iterators = Map.fromList [],
    valid = Set.fromList
      [
        TestHeaderHash
          `-7915818155603348863`,
        TestHeaderHash
          2173152789646624309,
        TestHeaderHash
          9122512639099877219],
    invalid = Map.fromList
      [
        _×_
          (TestHeaderHash
            `-1393368485677491682`)
          (_×_
            (ValidationError
              (ExtValidationErrorLedger
                InvalidBlock))
            (SlotNo 3)),
        _×_
          (TestHeaderHash
            128720366063791916)
          (_×_
            (ValidationError
              (ExtValidationErrorLedger
                InvalidBlock))
            (SlotNo 2))],
    currentSlot = SlotNo 3,
    maxClockSkew = 100000,
    isOpen = True},
  knownIters = RefEnv [],
  knownFollowers = RefEnv [],
  modelConfig = Opaque}

FAIL (99.21s)
          *** Failed! Falsified (after 50558 tests and 15 shrinks):
          MaxClockSkew 100000
          SmallChunkInfo (UniformChunkSize (ChunkSize {chunkCanContainEBB = True, numRegularBlocks = 14}))
          Commands
            { unCommands =
                [ Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 2173152789646624309
                                    , thPrevHash = GenesisHash
                                    , thBodyHash = TestBodyHash 590680769285548757
                                    , thSlotNo = SlotNo 0
                                    , thBlockNo = BlockNo 0
                                    , thChainLength = ChainLength 1
                                    , thIsEBB = EBB (EpochNo 0)
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 0
                                          , blockPointHash = TestHeaderHash 2173152789646624309
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 9122512639099877219
                                    , thPrevHash = BlockHash (TestHeaderHash 2173152789646624309)
                                    , thBodyHash = TestBodyHash 590681868797176966
                                    , thSlotNo = SlotNo 0
                                    , thBlockNo = BlockNo 1
                                    , thChainLength = ChainLength 2
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 2 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 0
                                          , blockPointHash = TestHeaderHash 9122512639099877219
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-7915818155603348863)
                                    , thPrevHash = BlockHash (TestHeaderHash 9122512639099877219)
                                    , thBodyHash = TestBodyHash 590680769285548757
                                    , thSlotNo = SlotNo 1
                                    , thBlockNo = BlockNo 2
                                    , thChainLength = ChainLength 3
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 3 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 1
                                          , blockPointHash = TestHeaderHash (-7915818155603348863)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-1393368485677491682)
                                    , thPrevHash = BlockHash (TestHeaderHash (-7915818155603348863))
                                    , thBodyHash = TestBodyHash 590682968308805178
                                    , thSlotNo = SlotNo 3
                                    , thBlockNo = BlockNo 3
                                    , thChainLength = ChainLength 4
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 1 , tbIsValid = False }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 1
                                          , blockPointHash = TestHeaderHash (-7915818155603348863)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash (-2651776708921877814)
                                    , thPrevHash = BlockHash (TestHeaderHash 2173152789646624309)
                                    , thBodyHash = TestBodyHash 590682968308805179
                                    , thSlotNo = SlotNo 0
                                    , thBlockNo = BlockNo 1
                                    , thChainLength = ChainLength 2
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 1 , tbIsValid = True }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 1
                                          , blockPointHash = TestHeaderHash (-7915818155603348863)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          AddBlock
                            TestBlock
                              { testHeader =
                                  TestHeader
                                    { thHash = TestHeaderHash 128720366063791916
                                    , thPrevHash = BlockHash (TestHeaderHash (-2651776708921877814))
                                    , thBodyHash = TestBodyHash 590682968308805178
                                    , thSlotNo = SlotNo 2
                                    , thBlockNo = BlockNo 2
                                    , thChainLength = ChainLength 3
                                    , thIsEBB = RegularBlock
                                    }
                              , testBody = TestBody { tbForkNo = 1 , tbIsValid = False }
                              }
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right
                                  (Point
                                     (At
                                        Block
                                          { blockPointSlot = SlotNo 1
                                          , blockPointHash = TestHeaderHash (-7915818155603348863)
                                          }))
                            }
                      }
                    []
                , Command
                    At
                      { unAt =
                          GetIsValid
                            (RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814)))
                      }
                    At
                      { unAt =
                          Resp
                            { getResp =
                                Right (IsValid IsValidResult { real = False , isValid = Nothing })
                            }
                      }
                    []
                ]
            }
          Model chain: Genesis :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash 9122512639099877219, thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590681868797176966, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 2, tbIsValid = True}} :> TestBlock {testHeader = TestHeader {thHash = TestHeaderHash (-7915818155603348863), thPrevHash = BlockHash (TestHeaderHash 9122512639099877219), thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 1, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}, testBody = TestBody {tbForkNo = 3, tbIsValid = True}}
          TraceEvents: TraceOpenEvent StartedOpeningDB
          TraceOpenEvent StartedOpeningImmutableDB
          TraceImmutableDBEvent NoValidLastLocation
          TraceOpenEvent (OpenedImmutableDB Origin 0)
          TraceOpenEvent StartedOpeningVolatileDB
          TraceOpenEvent OpenedVolatileDB
          TraceOpenEvent StartedOpeningLgrDB
          TraceLedgerReplayEvent (ReplayFromGenesis (ReplayGoal Origin))
          TraceOpenEvent OpenedLgrDB
          TraceInitChainSelEvent StartedInitChainSelection
          TraceInitChainSelEvent InitalChainSelected
          TraceOpenEvent (OpenedDB Origin Origin)
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)) (BlockNo 0) IsEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)}) (PushGoal {unPushGoal = RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)}) (Pushing {unPushing = RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)}))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 0, newTipTrigger = RealPoint (SlotNo 0) (TestHeaderHash 2173152789646624309)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList []}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)) (BlockNo 1) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)}) (PushGoal {unPushGoal = RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)}) (Pushing {unPushing = RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)}))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 0) (TestHeaderHash 2173152789646624309) (BlockNo 0), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 9122512639099877219, thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590681868797176966, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 0, newTipTrigger = RealPoint (SlotNo 0) (TestHeaderHash 9122512639099877219)}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 9122512639099877219, thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590681868797176966, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))) (BlockNo 2) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))}) (PushGoal {unPushGoal = RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))}) (Pushing {unPushing = RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))}))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 0) (TestHeaderHash 9122512639099877219) (BlockNo 1), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-7915818155603348863), thPrevHash = BlockHash (TestHeaderHash 9122512639099877219), thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 1, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}}]}})))
          TraceAddBlockEvent (AddedToCurrentChain [] (NewTipInfo {newTipPoint = RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863)), newTipEpoch = EpochNo 0, newTipSlotInEpoch = 1, newTipTrigger = RealPoint (SlotNo 1) (TestHeaderHash (-7915818155603348863))}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 9122512639099877219, thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590681868797176966, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}}) (AnchoredSeq {anchor = AnchorGenesis, unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 2173152789646624309, thPrevHash = GenesisHash, thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 0, thBlockNo = BlockNo 0, thChainLength = ChainLength 1, thIsEBB = EBB (EpochNo 0)}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash 9122512639099877219, thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590681868797176966, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}},MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-7915818155603348863), thPrevHash = BlockHash (TestHeaderHash 9122512639099877219), thBodyHash = TestBodyHash 590680769285548757, thSlotNo = SlotNo 1, thBlockNo = BlockNo 2, thChainLength = ChainLength 3, thIsEBB = RegularBlock}}]}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))) (BlockNo 3) IsNotEBB)
          TraceAddBlockEvent (TryAddToCurrentChain (RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))}) (PushGoal {unPushGoal = RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))}) (Pushing {unPushing = RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682))}))))
          TraceAddBlockEvent (AddBlockValidation (InvalidBlock (ExtValidationErrorLedger InvalidBlock) (RealPoint (SlotNo 3) (TestHeaderHash (-1393368485677491682)))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 1) (TestHeaderHash (-7915818155603348863)) (BlockNo 2), unanchorSeq = SFT {fromStrict = fromList []}})))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))) (BlockNo 1) IsNotEBB)
          TraceAddBlockEvent (TrySwitchToAFork (RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))) (ChainDiff {getRollback = 2, getSuffix = AnchoredSeq {anchor = Anchor (SlotNo 0) (TestHeaderHash 2173152789646624309) (BlockNo 0), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 0, headerFieldBlockNo = BlockNo 1, headerFieldHash = TestHeaderHash (-2651776708921877814)}}]}}}))
          TraceAddBlockEvent (AddedBlockToQueue (RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)) 1)
          TraceAddBlockEvent (AddedBlockToVolatileDB (RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)) (BlockNo 2) IsNotEBB)
          TraceAddBlockEvent (TrySwitchToAFork (RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)) (ChainDiff {getRollback = 2, getSuffix = AnchoredSeq {anchor = Anchor (SlotNo 0) (TestHeaderHash 2173152789646624309) (BlockNo 0), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 0, headerFieldBlockNo = BlockNo 1, headerFieldHash = TestHeaderHash (-2651776708921877814)}},MeasuredWith {unMeasuredWith = HeaderFields {headerFieldSlot = SlotNo 2, headerFieldBlockNo = BlockNo 2, headerFieldHash = TestHeaderHash 128720366063791916}}]}}}))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))}) (PushGoal {unPushGoal = RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)}) (Pushing {unPushing = RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))}))))
          TraceAddBlockEvent (AddBlockValidation (UpdateLedgerDbTraceEvent (StartedPushingBlockToTheLedgerDb (PushStart {unPushStart = RealPoint (SlotNo 0) (TestHeaderHash (-2651776708921877814))}) (PushGoal {unPushGoal = RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)}) (Pushing {unPushing = RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916)}))))
          TraceAddBlockEvent (AddBlockValidation (InvalidBlock (ExtValidationErrorLedger InvalidBlock) (RealPoint (SlotNo 2) (TestHeaderHash 128720366063791916))))
          TraceAddBlockEvent (AddBlockValidation (ValidCandidate (AnchoredSeq {anchor = Anchor (SlotNo 0) (TestHeaderHash 2173152789646624309) (BlockNo 0), unanchorSeq = SFT {fromStrict = fromList [MeasuredWith {unMeasuredWith = TestHeader {thHash = TestHeaderHash (-2651776708921877814), thPrevHash = BlockHash (TestHeaderHash 2173152789646624309), thBodyHash = TestBodyHash 590682968308805179, thSlotNo = SlotNo 0, thBlockNo = BlockNo 1, thChainLength = ChainLength 2, thIsEBB = RegularBlock}}]}})))

          PostconditionFailed "AnnotateC \"real response didn't match model response\" (PredicateC (Resp {getResp = Right (IsValid (IsValidResult {real = True, isValid = Just True}))} :/= Resp {getResp = Right (IsValid (IsValidResult {real = False, isValid = Nothing}))}))" /= Ok
          Use --quickcheck-replay=455411 to reproduce.
          Use -p '/ChainDB q-s-m.sequential/' to rerun this test only.

1 out of 40 tests failed (103.73s)
```
</details>

### PR DESCRIPTION
**Pull request by bartfrenk**
# Description

Fix ChainDB QSM test by incorporating already detected invalid blocks into the model's logic that orders the candidate chains according to the way the actual implementation would try them.

Suppose that we have the candidate chains [GABCd, GAEf] in which lower case letters indicate invalid blocks, and in which the ChainDB already knows that d is invalid, and f is the last block that has been added.

The model implementation would:
1. order the candidates [GABCd, GAEf] (attempting to mimic the way the actual implementation tries chains),
2. truncate the chains to their valid prefixes [GABC, GAE]
3. select GABC as the current chain.  
It would not detect valid blocks in GAEf, in particular E.

The actual implementation already knows that d is invalid and would start from [GABC, GAEf], and the order in which it would try chains is [GAEf, GABC]. In the process it would detect that E is valid.

The solution proposed here changes 1. to already take into account known invalid blocks (we are keeping track of those in the model anyway).

Closes #3689.

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [x] New tests are added if needed and existing tests are updated
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

### CODE REVIEW

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 1]
```diff
@@ -876,8 +877,11 @@ validChains cfg m bs =
     -- first, which results in the valid chain A->B', which is then chosen
     -- over the equally preferable A->B as it will be the first in the list
     -- after a stable sort.
-    sortChains $ chains bs
+    sortChains $ pruneKnownInvalid (invalid m) <$> chains bs
   where
+    pruneKnownInvalid invalidBlocks chain =
+      Chain.takeWhileChain (\b -> blockHash b `Map.notMember` invalidBlocks) chain
```
Comment (amesgen) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:883]: Let's include a comment why we do this, sth along the lines of

> We don't want known-invalid blocks to influence the sorting of candidate chains.

Also a small style thing: What about making `invalidBlocks` a `where` binding under `pruneKnownInvalid`?

**Review by amesgen — APPROVED** [review]
It is great to see that #3689 can fixed so non-invasively, excellent identification of the core reason!

LGTM; only minor comments below.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 2]
```diff
@@ -876,8 +876,12 @@ validChains cfg m bs =
     -- first, which results in the valid chain A->B', which is then chosen
     -- over the equally preferable A->B as it will be the first in the list
     -- after a stable sort.
```
Comment (Jasagredo) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs:878]: I would suggest enlarging this comment to explain the new behavior

**Review by Jasagredo — APPROVED** [review]
Very nice way to solve this indeed. LGTM.
