### PR TITLE
Fix 3784 issue

### LINKED ISSUE #3784: diffusion target established local property failure
```
        Property violated at: Time 115.464830553955s
        Invalid signal value:
        (fromList [TestAddress 0.1.216.208:65534,TestAddress 0.3.40.152:65532],fromList [],fromList [TestAddress 0.1.216.208:65534,TestAddress 122.209.126.89:65497],fromList [TestAddress 0.1.216.208:65534],True,fromList [TestAddress 0.3.40.152:65532],fromList [TestAddress 0.3.40.152:65532])
        
        Use --quickcheck-replay=628044 to reproduce.
        Use -p '/diffusion target established local/' to rerun this test only.
```

[`IOSim` event trace](https://github.com/input-output-hk/ouroboros-network/files/8808672/Untitled.txt)

### PR DESCRIPTION
**Pull request by bolt12**
# Description

This PR fixes #3784 . It appears the `DiffTime` used for checking opportunities aren't ignored for too long is not correctly tuned. The solution consists in slightly increasing the time window considered.

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [x] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [x] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

**Comment by coot** [comment]
I put the `description` ahead of `Checklist` (anything after `#Checklist` will be removed by `bors`).

**Review by coot — APPROVED** [review]

File: ouroboros-network/test/Test/Ouroboros/Network/PeerSelection.hs [hunk 1]
```diff
@@ -1971,7 +1971,7 @@ prop_governor_target_established_local env =
         promotionOpportunitiesIgnoredTooLong :: Signal (Set PeerAddr)
         promotionOpportunitiesIgnoredTooLong =
           Signal.keyedTimeout
-            10 -- seconds
+            15 -- seconds
```
Comment (coot) [inline ouroboros-network/test/Test/Ouroboros/Network/PeerSelection.hs:1974]: it would be good to explain why `15` seconds is enough.

**Comment by bolt12** [comment]
bors merge

**Comment by bolt12** [comment]
bors merge
