### PR TITLE
Fix dns re-initialisation on Windows

### LINKED ISSUE #3968: DNS library errors on Windows
```
[34m[DESKTOP-:cardano.node.PublicRootPeers:Info:212][0m [2022-08-18 12:45:55.53 UTC] TracePublicRootRelayAccessPoint [RelayAccessDomain "preview-node.world.dev.cardano.org" 30002]
[34m[DESKTOP-:cardano.node.PublicRootPeers:Info:212][0m [2022-08-18 12:45:55.53 UTC] TracePublicRootRelayAccessPoint [RelayAccessDomain "preview-node.world.dev.cardano.org" 30002]
[31m[DESKTOP-:cardano.node.PeerSelection:Error:52][0m [2022-08-18 12:45:55.53 UTC] TracePublicRootsFailure /etc/resolv.conf: getModificationTime:CreateFile "\\\\?\\C:\\etc\\resolv.conf": does not exist (Nie można odnaleźć określonego pliku.) (-5) 32s
```

The node was started using this [topology file](https://book.world.dev.cardano.org/environments/preview/topology.json).

### PR DESCRIPTION
**Pull request by coot**
# Description

Fixes #3968 and refactors `resolverResource` and `asyncResolverResource` functions.

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs [hunk 1]
```diff
@@ -234,45 +238,49 @@ asyncResolverResource resolvConf =
...
-                  pure (Right resolver', go filePath resourceVar)
-          `catches` handlers filePath resourceVar
-#else
-asyncResolverResource resolvConf = resolverResource resolvConf
-#endif
+              then return resolver
+              else do
+              resolver' <- ExceptT $ (Right <$> getResolver resolvConf)
+                                     `catches` handlers
+              lift $ atomically (writeTVar resourceVar (TimedResolver resolver' modTime'))
```
Comment (bolt12) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs:274]: Is this lift necessary? Can't we perform this outside `ExceptT` in case of success (`Right`) ? it could avoid one extra dependency

**Review by bolt12 — APPROVED** [review]
LGTM just a minor comment about commit squashing and `lift` use

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs (hunk 1 above)
Comment (coot) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs:274]: I thought we don't have `MonadSTM` instance for `ErrorT`, but we actually have [one](https://github.com/input-output-hk/io-sim/blob/main/io-classes/src/Control/Monad/Class/MonadSTM.hs#L1049), maybe I need to update `io-sim` hash.

I think we cannot take it out without the if condition, and that's probably not worth it.

Comment (coot) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs:274]: we can remove `lift` but we'll need [`castStrictTVar`](https://github.com/input-output-hk/io-sim/blob/main/strict-stm/src/Control/Monad/Class/MonadSTM/Strict.hs?plain=1#L120-L123).

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs [hunk 2]
```diff
@@ -92,26 +93,26 @@ constantResource :: Applicative m => a -> Resource m err a
 constantResource a = Resource (pure (Right a, constantResource a))
 
 
-#if !defined(mingw32_HOST_OS)
```
[the remark this answers is not in the document]
Comment (coot) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs]: Hmm, I wonder why the CPP were removed, they shoudn't.  Maybe `stylish-haskell` removed it :/.

[the remark this answers is not in the document]
Comment (coot) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS/DNSActions.hs]: Fixed.

**Comment by coot** [comment]
bors merge
