### PR TITLE
ChainDB: allow EBB with same block number as the immutable block

### LINKED ISSUE #1624: Chain DB can't add the next EBB when the VolatileDB is empty
Say the VolatileDB has been wiped/corrupted. Now the tip of our current chain is the tip of the ImmutableDB. Say that tip is the last block of some epoch. When we now try to add the next EBB, that EBB has the same block number as the immutable block's tip, and is thus ignored. Which means we *can't make progress anymore*. Restarting and rewiping the VolatileDB doesn't help.

The bug is here: https://github.com/input-output-hk/ouroboros-network/blob/c0f1e1cc2d61e850c2f422272effea4047c58ba9/ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ChainSel.hs#L189

The `=` in the `<=` excludes EBBs. The second condition is already sign there's something wrong, it just special cases the very first EBB.

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1624.

### CODE REVIEW

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 1]
```diff
@@ -364,12 +361,7 @@ addBlock cfg blk m
   where
     secParam = protocolSecurityParam cfg
 
-    -- If we switch to PBFT for these tests, this case is not required anymore
-    -- TODO: We should not make assumptions about the underlying
-    -- ledger. We will fix this in
-    -- <https://github.com/input-output-hk/ouroboros-network/issues/1571>
```
Comment (mrBliss) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: This special case is gone without #1571. Unverified: maybe we only needed it to not ignore the EBB, but we still don't adopt EBBs immediately when adding them, only when their successor is added? If that's true, then PBFT would change that, but then it is not that important to make that change.

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model/Test.hs [hunk 2]
```diff
@@ -93,3 +94,10 @@ prop_between_currentChain bt =
     from     = StreamFromExclusive genesisPoint
     to       = StreamToInclusive $ M.tipPoint model
     secParam = protocolSecurityParam singleNodeTestConfig
+
+{-------------------------------------------------------------------------------
+  Orphan instances
+-------------------------------------------------------------------------------}
+
+instance ModelSupportsBlock TestBlock where
+  isEBB = const IsNotEBB
```
Comment (mrBliss) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model/Test.hs]: A bit annoying: this TestBlock lives in `test-util`, so it can implements `ModelSupportsBlock` (`test-consensus`) itself, hence the orphans :disappointed:.

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ChainSel.hs [hunk 3]
```diff
@@ -306,7 +310,11 @@ chainSelectionForBlock cdb@CDB{..} blockCache hdr = do
     if
       -- The chain might have grown since we added the block such that the
       -- block is older than @k@.
-      | At (blockNo hdr) <= immBlockNo && blockNo hdr /= 0 ->
+      | At (blockNo hdr) <= immBlockNo &&
+        -- Exception: the block we're adding is the EBB with the same block
+        -- number as the immutable tip. This can only happen when the
+        -- VolatileDB was corrupted.
+        not (At (blockNo hdr) == immBlockNo && cdbIsEBB hdr == IsEBB) ->
```
Comment (edsko) [inline ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ChainSel.hs]: Should we introduce an `olderThanK` predicate, document it with this comment, and then use that here and above rather than duplicate this logic?

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs (hunk 1 above)
Comment (edsko) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: Hang on, didn't we verify this? And it still failed? What am I getting confused with?

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 4]
```diff
@@ -326,18 +326,15 @@ advanceCurSlot cfg curSlot m =
...
     advance slot m' = m' { currentSlot = slot `max` currentSlot m' }
 
-addBlock :: forall blk. ProtocolLedgerView blk
+addBlock :: forall blk. (ProtocolLedgerView blk, ModelSupportsBlock blk)
          => NodeConfig (BlockProtocol blk)
          -> blk
          -> Model blk -> Model blk
 addBlock cfg blk m
     -- If the block is as old as the tip of the ImmutableDB, i.e. older than
-    -- @k@, we ignore it, as we can never switch to it. TODO what about EBBs?
```
Comment (edsko) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: What about EBBs indeed :angry:

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs (hunk 1 above)
Comment (edsko) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: (This will have a minor conflict with my PR I guess.)

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs [hunk 5]
```diff
@@ -326,18 +326,15 @@ advanceCurSlot cfg curSlot m =
...
-  | At (Block.blockNo blk) <= immutableBlockNo secParam m
-    -- Unless we're adding the first block to the empty chain: the empty chain
-    -- has the same block number as the genesis EBB, i.e. 0, so we don't want
-    -- to ignore it in this case.
-  , not addingGenesisEBBToEmptyDB
+    -- @k@, we ignore it, as we can never switch to it.
+  | At (Block.blockNo blk) <= immBlockNo
+  , not (At (Block.blockNo blk) == immBlockNo && isEBB (getHeader blk) == IsEBB)
```
Comment (edsko) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: So this is basically the same change from the real DB to the model.

Comment (mrBliss) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: Indeed.

Comment (mrBliss) [reply ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/Model.hs]: In my last version, I reuse the new function from `.ChainSel` in the model.

**Comment by mrBliss** [comment]
I have created #1628 for testing this properly. Note that I have already verified it manually using `cardano-node` (I discovered this bug when I wiped the VolatileDB of a `cardano-node`).
