### PR TITLE
ImmutableDB.Iterator: allocate handles in the ResourceRegistry

### LINKED ISSUE #1543: ImmutableDB is leaking file handles
On master (commit 62d8e669), this test case fails with `ImmutableDB is leaking file handles`.

```
          let ncn5 = NumCoreNodes 5 in
          prop_simple_real_pbft_convergence NoEBBs (SecurityParam 2) TestConfig
            { numCoreNodes = ncn5
            -- Still fails if I increase numSlots.
            , numSlots     = NumSlots 54
            , nodeJoinPlan = NodeJoinPlan $ Map.fromList
              [(CoreNodeId 0,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 1,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 2,SlotNo {unSlotNo = 0})
              ,(CoreNodeId 3,SlotNo {unSlotNo = 53}),(CoreNodeId 4,SlotNo {unSlotNo = 53})
              ]
              -- Passes if I drop either of these restarts.
            , nodeRestarts = NodeRestarts (Map.fromList [(SlotNo {unSlotNo = 50},Map.fromList [(CoreNodeId 0,NodeRestart)]),(SlotNo {unSlotNo = 53},Map.fromList [(CoreNodeId 3,NodeRestart)])])
            , nodeTopology = meshNodeTopology ncn5
              -- Slot length of 19s passes, and 21s also fails; I haven't seen this matter before.
            , slotLengths  = singletonSlotLengths (slotLengthFromSec 20)
            , initSeed     = Seed {getSeed = (15062108706768000853,6202101653126031470,15211681930891010376,1718914402782239589,12639712845887620121)}
            }
```

With some instrumentation, I determined that node c0 leaks one ImmDB file handle, for path @00000.epoch@, read only, offset at 0. It was opened by a `ChainSyncServer` thread.

The test case seems somewhat fragile, since the 'slotLengths' value seems to matter.

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1543.

The ChainDB.Iterators and ChainDB.Readers use ImmutableDB.Iterators internally. Both take a ResourceRegistry to allocate the ImmutableDB.Iterator in so that the ImmutableDB.Iterator and the open handle it contains is closed when an exception occurs.

If an exception occurs at the wrong time while opening an ImmutableDB.Iterator, after opening the handle, we might leak the handle. Fix this by directly allocating the handle in the ResourceRegistry instead of the ImmutableDB.Iterator that refers to the handle.

### CODE REVIEW

File: ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs [hunk 1]
```diff
@@ -503,24 +517,27 @@ iteratorCloseImpl
...
         atomically $ writeTVar itState IteratorStateExhausted
-        hClose itEpochHandle
-  where
-    HasFS { hClose } = itHasFS
+        -- NOTE: we must use 'unsafeRelease', as we might be closing the
+        -- iterator from a different thread than the one in which it was
+        -- opened. For example, when closing the ImmutableDB/ChainDB from the
+        -- main thread, we'll close all open iterators, each of them opened in
+        -- a different thread.
+        unsafeRelease itEpochKey
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: Comment is wrong (same for other `unsafeRelease`): the reason this was needed is because in the consensus tests, the protocol threads are spawned in a different `ResourceRegistry` than the ChainDB, see #1390. We're not going to fix that in this PR, but add a comment: "this is dangerous, because this allows the iterator to be used by a thread not spawned by this registry, so the iterator can disappear before the thread is terminated".

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: Add a comment on #1390 about this.

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: I'm currently assuming that `iteratorClose` is sometimes called from a different thread than the one that created that registry. E.G. at a glance, it looks like `ChainDB.Impl.implIteratorNext` could be called from a spawned thread, and that calls `ImmDB.iteratorClose`.

So, even if iterators were managed by the ChainDB registry, wouldn't we see `ResourceRegistryUsedFromUnknownThread` without `unsafeRelease`? Or is my assumption wrong?

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: My comment (in the code) was wrong.

A resource can in fact be released from another thread, *as long as that thread has been spawned by the same registry*.

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: Ah ha! I was conflating the two error conditions in just the same way as the comment.

The name `ResourceRegistryUsedFromUnknownThread` is not wrong, but it does admit this misinterpretation. `ResourceRegistryUsedFromUntrackedThread` (or just the full `ResourceRegistryUsedFromThreadNotInRegistry`) would be clearer in this aspect, in hindsight.

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: > The name `ResourceRegistryUsedFromUnknownThread` is not wrong, but it does admit this misinterpretation. `ResourceRegistryUsedFromUntrackedThread` (or just the full `ResourceRegistryUsedFromThreadNotInRegistry`) would be clearer in this aspect, in hindsight.

Agreed. Good idea!

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Storage/ImmutableDB/Impl/Iterator.hs]: I have renamed `ResourceRegistryUsedFromUnknownThread` to `ResourceRegistryUsedFromUntrackedThread` (and updated the comments) in a separate commit.
