### PR TITLE
Test & fix backwards compatibility between Byron and Cardano

### LINKED ISSUE #2361: Test compatibility between Byron and Cardano with the hard fork disabled
When in the Byron era of `CardanoBlock` with as version `HardForkNodeToNode/ClientDisabled`, the serialisation format should be compatible with that of `ByronBlock`, so that we can still communicate with other nodes that have not yet been updated.

We should test this binary compatibility by running the roundtrip tests using the encoders of `ByronBlock` and the decoders of `CardanoBlock`, and vice versa. By introducing a newtype wrapper for each direction, we should be able to reuse the existing roundtrip test skeletons.

### PR DESCRIPTION
**Pull request by mrBliss**
Test backwards compatibility between Byron and Cardano

Fixes #2361.

A node running `CardanoBlock` can communicate with older nodes that run
`ByronBlock`, until the hard fork happens (as the other nodes won't support
Shelley). Test that we're actually backwards compatible.

This test did exactly what it was supposed to do: it found a bug!

Some idiot broke backwards compatibility in #2349. We were no longer able to exchange queries via the `LocalStateQuery` protocol
with a Byron-only node. Fix it.

### CODE REVIEW

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 1]
```diff
@@ -0,0 +1,695 @@
...
+tests :: TestTree
+tests = adjustOption reduceTests $
+    testGroup "Byron compatibility" [
+        testGroup "Byron to Cardano" [
+              testProperty "roundtrip block" $
+                roundtrip' @ByronToCardano
+                  (encodeDisk byronToCardanoCodeConfig)
+                  (decodeDisk byronToCardanoCodeConfig)
+            , testGroup "SerialiseNodeToNode" $
+                roundtrip_SerialiseNodeToNode   byronToCardanoCodeConfig
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:69]: Don't align.

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 2]
```diff
@@ -0,0 +1,695 @@
...
+    fromCardano' :: f (CardanoBlock Crypto) -> b2c
+    fromCardano' = fromCardano . coerce
+
+instance SerialiseNodeToNode ByronToCardano ByronToCardano where
+  encodeNodeToNode = encodeNodeToNodeB2C (Proxy @I) unB2C
+  decodeNodeToNode = decodeNodeToNodeB2C (Proxy @I) (\(BlockByron blk) -> B2C blk)
+
+instance SerialiseNodeToNode ByronToCardano (Serialised ByronToCardano) where
+  encodeNodeToNode = encodeNodeToNodeB2C (Proxy @Serialised) id
+  decodeNodeToNode = decodeNodeToNodeB2C (Proxy @Serialised) (\(Serialised bytes) -> Serialised bytes)
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:281]: Just `id`?

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 3]
```diff
@@ -0,0 +1,695 @@
...
+     , Coercible byron (f ByronBlock)
+     )
+  => Proxy f
+  -> (b2c -> byron)
+  -> CodecConfig ByronToCardano
+  -> BlockNodeToClientVersion ByronToCardano
+  -> b2c
+  -> Encoding
+encodeNodeToClientB2C _ toByron (CodecConfigB2C ccfg) () x =
+      encodeNodeToClient ccfg byronNodeToClientVersion (toByron' x)
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:321]: Indentation

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 4]
```diff
@@ -0,0 +1,695 @@
...
+     , Coercible cardano (f (CardanoBlock Crypto))
+     )
+  => Proxy f
+  -> (cardano -> b2c)
+  -> CodecConfig ByronToCardano
+  -> BlockNodeToClientVersion ByronToCardano
+  -> forall s. Decoder s b2c
+decodeNodeToClientB2C _ fromCardano (CodecConfigB2C ccfg) () =
+      fromCardano' <$>
+        decodeNodeToClient (toCardanoCodecConfig ccfg) cardanoNodeToClientVersion
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:338]: Indentation

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 5]
```diff
@@ -0,0 +1,695 @@
...
+pb = Proxy
+
+toCardanoCodecConfig ::
+     CodecConfig ByronBlock
+  -> CodecConfig (CardanoBlock Crypto)
+toCardanoCodecConfig codecConfigByron =
+    CardanoCodecConfig codecConfigByron ShelleyCodecConfig
+
+instance Arbitrary a => Arbitrary (WithVersion () a) where
+  arbitrary = WithVersion () <$> arbitrary
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:129]: Move to the definition of `WithVersion`

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 6]
```diff
@@ -0,0 +1,695 @@
...
+{-# LANGUAGE GADTs                 #-}
+{-# LANGUAGE MultiParamTypeClasses #-}
+{-# LANGUAGE RankNTypes            #-}
+{-# LANGUAGE ScopedTypeVariables   #-}
+{-# LANGUAGE StandaloneDeriving    #-}
+{-# LANGUAGE TypeApplications      #-}
+{-# LANGUAGE TypeFamilies          #-}
+{-# LANGUAGE UndecidableInstances  #-}
+
+{-# OPTIONS_GHC -Wno-orphans -Wno-incomplete-uni-patterns #-}
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:12]: Still orphans?

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs [hunk 7]
```diff
@@ -0,0 +1,695 @@
...
+unNestedCtxt_B2C (NestedCtxt_B2C ctxt) = ctxt
+
+type instance HeaderHash ByronToCardano = HeaderHash ByronBlock
+type instance ApplyTxErr ByronToCardano = ApplyTxErr ByronBlock
+
+instance HasNetworkProtocolVersion ByronToCardano
+
+instance ConvertRawHash ByronToCardano where
+  toRawHash   _ = toRawHash   pb
+  fromRawHash _ = fromRawHash pb
```
[the remark this answers is not in the document]
Comment (mrBliss) [reply ouroboros-consensus-cardano/test/Test/Consensus/Cardano/ByronCompatibility.hs:165]: Yes, a superclass constraint of `SerialiseNodeToNodeConstraints`.

**Comment by mrBliss** [comment]
bors merge

**Comment by mrBliss** [comment]
bors merge
