### PR TITLE
Fix issue #4491

### LINKED ISSUE #4491: Issue with local roots which use more than one domain name
The node fails to maintain a hot connection to all configured local root peers, if more than 1 DNS name is used in a single group.

Splitting the relays up into different access points (groups) works as a workaround.

### PR DESCRIPTION
**Pull request by bolt12**
Updates the result local root groups TVar with up to date information instead of static one.

Also adds & fixes tests to check for this particular case.

Closes #4491

### CODE REVIEW

File: ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs [hunk 1]
```diff
@@ -707,6 +728,18 @@ prop_local_updatesDomainsCorrectly mockRoots@(MockRoots lrp _ _ _)
...
+  prop_local_updatesDomainsCorrectly
+    (MockRoots [ (2, Map.fromList [(RelayAccessDomain "dns1" 00001, DoAdvertisePeer)
+               , (RelayAccessDomain "dns2" 00000, DoAdvertisePeer)])
+               ]
+               (singletonScript (Map.fromList [ ("dns1", [("0.0.0.0", 0)])
+                                              , ("dns2", [("0.0.0.1", 0)])]))
+               Map.empty
+               (singletonScript Map.empty))
+    (singletonScript (DNSTimeout 1000))
+    (singletonScript (DNSLookupDelay 0))
```
Comment (coot) [inline ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs:742]: Is this covered by `prop_local_updatesDomainsCorrectly`? If so, then do we need this?

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS.hs [hunk 2]
```diff
@@ -246,7 +243,7 @@ localRootPeersProvider tracer
                     -- configured IPs, that's why we get the entry from the
                     -- statically configured rootPeersGroups list.
                     --
-                let (target, entry)  = rpgStatic `Seq.index` index
+                let (target, entry)  = rootPeersGroups `Seq.index` index
```
Comment (coot) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS.hs:246]: What about the comment above?

File: ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs (hunk 1 above)
Comment (bolt12) [reply ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs:742]: ugh I responded via email and it ended up in a different place. Actual reply:

It is now, I just used it to make sure we were covering the case that would
lead to the bug. I can remove it!

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS.hs (hunk 2 above)
Comment (bolt12) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS.hs:246]: Needs to be removed!

Comment (bolt12) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/RootPeersDNS.hs:240]: Done!

File: ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs (hunk 1 above)
Comment (bolt12) [reply ouroboros-network/test/Test/Ouroboros/Network/PeerSelection/RootPeersDNS.hs]: Done!

**Comment by bolt12** [comment]
bors merge

**Comment by coot** [comment]
bors merge
