### PR TITLE
Parameterise error types over blk for deriving instances 

### LINKED ISSUE #2598: Parameterise error types over blk instead of using existentials
The `Eq` instances for types like `ImmutableDBError`, `ChainDbError`, ..., are a major PITA to write because of the existentials. We just want to use `deriving (Eq)`.

The reason why we didn't parameterise over `blk` is that in the `ErrorPolicy` we'd have to pick the right instantiation of each exception type, otherwise it wouldn't handle it. Because the error types had different instantiations (`ImmutableDBError (HeaderHash blk)` vs `ChainDbError blk`), it was easy to get them wrong and the type checker didn't help.

After #2534, all exceptions can be parameterised by just `blk`, so if we parameterise the `ErrorPolicy` by `blk` too, we can get rid of those annoying existentials (and a bunch of `Proxy`s).

### PR DESCRIPTION
**Pull request by jutaro**
Fixes #2598.

### CODE REVIEW

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs [hunk 1]
```diff
@@ -27,8 +33,8 @@ import           Ouroboros.Consensus.Util.ResourceRegistry
                      (RegistryClosedException, ResourceRegistryThreadException,
                      TempRegistryException)
 
-consensusErrorPolicy :: ErrorPolicies
-consensusErrorPolicy = ErrorPolicies {
+consensusErrorPolicy :: forall blk. (Typeable blk, StandardHash blk) => Proxy blk -> ErrorPolicies
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs:36]: Am I correct in remembering that you said you don't mind lines longer than 80 characters?

Sorry to disappoint you, but we do try to stick to 80 characters, unless it is helpful in combination with alignment :grinning:.

When a type signature is too long, we use the following style:

```suggestion
consensusErrorPolicy ::
     forall blk. (Typeable blk, StandardHash blk)
  => Proxy blk
  -> ErrorPolicies
```

(When there are too many constraints, we wrap those too).

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs [hunk 2]
```diff
@@ -27,8 +33,8 @@ import           Ouroboros.Consensus.Util.ResourceRegistry
                      (RegistryClosedException, ResourceRegistryThreadException,
                      TempRegistryException)
 
-consensusErrorPolicy :: ErrorPolicies
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs:30]: I hadn't even considered this approach (i.e., not parameterising `ErrorPolicies` by `blk`), good idea! :+1:

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 3]
```diff
@@ -1,6 +1,10 @@
+{-# LANGUAGE AllowAmbiguousTypes #-}
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:1]: This should not be necessary if you use `Proxy`.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 4]
```diff
@@ -1,6 +1,10 @@
...
 {-# LANGUAGE LambdaCase          #-}
 {-# LANGUAGE NamedFieldPuns      #-}
+{-# LANGUAGE RankNTypes          #-}
 {-# LANGUAGE ScopedTypeVariables #-}
+
+
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:7]: Just one is enough.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 5]
```diff
@@ -10,11 +14,15 @@ module Ouroboros.Consensus.Node.Exit
   , toExitReason
   ) where
 
+import           Data.Proxy (Proxy)
+import           Data.Typeable (Typeable)
+
 import           Control.Exception (AsyncException (..), SomeException,
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:20]: Convention: group these together.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 6]
```diff
@@ -10,11 +14,15 @@ module Ouroboros.Consensus.Node.Exit
...
                      fromException)
 
 import           Control.Monad.Class.MonadAsync (ExceptionInLinkedThread (..))
 
+import           Ouroboros.Consensus.Block (StandardHash)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:25]: Convention: separate `Ouroboros.Consensus` imports from `Ouroboros.Consensus.Storage` imports. (In that order)

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 7]
```diff
@@ -97,30 +105,30 @@ data ExitReason =
 
 -- | Return the 'ExitReason' for the given 'SomeException'. Defaults to
 -- 'Other'.
-toExitReason :: SomeException -> ExitReason
-toExitReason e
+toExitReason :: forall blk. (Typeable blk, StandardHash blk) => Proxy blk -> SomeException -> ExitReason
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:108]: Same remark as for the `ErrorPolicy`.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs [hunk 8]
```diff
@@ -97,30 +105,30 @@ data ExitReason =
...
+toExitReason blk e
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Exit.hs:109]:
```suggestion
toExitReason pb e
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 9]
```diff
@@ -1,13 +1,21 @@
-{-# LANGUAGE OverloadedStrings #-}
+{-# LANGUAGE AllowAmbiguousTypes #-}
+{-# LANGUAGE OverloadedStrings   #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+
+
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:5]: Just one blank line.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 10]
```diff
@@ -1,13 +1,21 @@
-{-# LANGUAGE OverloadedStrings #-}
+{-# LANGUAGE AllowAmbiguousTypes #-}
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:1]: Same remark as above. In fact, `AllowAmbiguousTypes` is a pragma non grata in the consensus :slightly_smiling_face: 

I found only one use of it in master and that can and should be removed.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 11]
```diff
@@ -1,13 +1,21 @@
...
   ( createMarkerOnCleanShutdown
   , hasCleanShutdownMarker
   , createCleanShutdownMarker
   , removeCleanShutdownMarker
   ) where
 
+import           Data.Proxy (Proxy)
+import           Data.Typeable (Typeable)
+
 import           Control.Monad (unless, when)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:16]: Convention: group these together.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 12]
```diff
@@ -68,8 +77,8 @@ removeCleanShutdownMarker hasFS =
 
 -- | Return 'True' if the given exception indicates that recovery of the
 -- database is required on the next startup.
-exceptionRequiresRecovery :: SomeException -> Bool
-exceptionRequiresRecovery e = case toExitReason e of
+exceptionRequiresRecovery :: forall blk. (StandardHash blk, Typeable blk) => Proxy blk -> SomeException -> Bool
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:80]: Too long.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 13]
```diff
@@ -29,12 +37,13 @@ cleanShutdownMarkerFile = mkFsPath ["clean"]
...
-  :: IOLike m
-  => HasFS m h
+  :: (IOLike m, StandardHash blk, Typeable blk)
+  => Proxy blk
+  -> HasFS m h
   -> m a  -- ^ Action to run
   -> m a
-createMarkerOnCleanShutdown mp = onExceptionIf
-    (not . exceptionRequiresRecovery)
+createMarkerOnCleanShutdown blk mp = onExceptionIf
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:45]: `pb`

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs [hunk 14]
```diff
@@ -68,8 +77,8 @@ removeCleanShutdownMarker hasFS =
 
 -- | Return 'True' if the given exception indicates that recovery of the
 -- database is required on the next startup.
-exceptionRequiresRecovery :: SomeException -> Bool
-exceptionRequiresRecovery e = case toExitReason e of
+exceptionRequiresRecovery :: forall blk. (StandardHash blk, Typeable blk) => Proxy blk -> SomeException -> Bool
+exceptionRequiresRecovery blk e = case toExitReason blk e of
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/Recovery.hs:81]: `pb`

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs [hunk 15]
```diff
@@ -346,8 +347,8 @@ takeSnapshot lgrDB@LgrDB{ cfg, tracer, hasFS } = wrapFailure $ do
                               (encodeDisk ccfg)
                               (encodeDisk ccfg)
 
-trimSnapshots :: MonadCatch m => LgrDB m blk -> m [DiskSnapshot]
-trimSnapshots LgrDB { diskPolicy, tracer, hasFS } = wrapFailure $
+trimSnapshots :: forall m blk. (MonadCatch m, StandardHash blk, Typeable blk) => LgrDB m blk -> m [DiskSnapshot]
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs:350]: Too long + `HasHeader blk`

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs [hunk 16]
```diff
@@ -472,8 +473,11 @@ garbageCollectPrevApplied LgrDB{..} slotNo = modifyTVar varPrevApplied $
 
 -- | Wrap exceptions that may indicate disk failure in a 'ChainDbFailure'
 -- exception using the 'LgrDbFailure' constructor.
-wrapFailure :: forall m x. MonadCatch m => m x -> m x
-wrapFailure k = catch k rethrow
+wrapFailure :: forall m x blk. (MonadCatch m, Typeable blk, StandardHash blk) =>
+     Proxy blk
+  -> m x
+  -> m x
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs:479]:
```suggestion
wrapFailure ::
     forall m x blk. (MonadCatch m, HasHeader blk) 
  => Proxy blk
  -> m x
  -> m x
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Reader.hs [hunk 17]
```diff
@@ -50,24 +51,24 @@ import           Ouroboros.Consensus.Storage.Serialisation
 --
 -- Otherwise, execute the given function on the 'ChainDbEnv'.
 getReader
-  :: forall m blk r. (IOLike m, HasCallStack)
+  :: forall m blk r. (IOLike m, HasCallStack, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Reader.hs:54]: I think the following is shorter and is fine for this module:
```suggestion
  :: forall m blk r. (IOLike m, HasCallStack, HasHeader blk)
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Reader.hs [hunk 18]
```diff
@@ -50,24 +51,24 @@ import           Ouroboros.Consensus.Storage.Serialisation
...
         if readerOpen
           then return env
-          else throwIO ClosedReaderError
+          else throwIO (ClosedReaderError :: ChainDbError blk)
     f env
 
 -- | Variant 'of 'getReader' for functions taking one argument.
 getReader1
-  :: forall m blk a r. IOLike m
+  :: forall m blk a r. (IOLike m, Typeable blk, StandardHash blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Reader.hs:71]: Same comment about `HasHeader blk`

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs [hunk 19]
```diff
@@ -472,8 +473,11 @@ garbageCollectPrevApplied LgrDB{..} slotNo = modifyTVar varPrevApplied $
...
+wrapFailure _ k = catch k rethrow
   where
     rethrow :: FsError -> m x
-    rethrow err = throwIO $ LgrDbFailure err
+    rethrow err = throwIO $ (LgrDbFailure err :: ChainDbFailure blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/LgrDB.hs:483]: We prefer `-XTypeApplications` in such cases:
```suggestion
    rethrow err = throwIO $ LgrDbFailure @blk err
```
(The same comment applies to a bunch of other places)

File: ouroboros-consensus/src/Ouroboros/Consensus/Node.hs [hunk 20]
```diff
@@ -381,12 +381,13 @@ newtype LastShutDownWasClean = LastShutDownWasClean Bool
...
-stdWithCheckedDB :: forall a.
-     FilePath
+stdWithCheckedDB :: forall blk a. (StandardHash blk, Typeable blk) =>
+     Proxy blk
+  -> FilePath
   -> NetworkMagic
   -> (LastShutDownWasClean -> IO a)  -- ^ Body action with last shutdown was clean.
   -> IO a
-stdWithCheckedDB databasePath networkMagic body = do
+stdWithCheckedDB blk databasePath networkMagic body = do
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node.hs:390]: We have a convention to use `pb` (or `p`) to name such proxies. `blk` is typically used for actual blocks.

File: ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs [hunk 21]
```diff
@@ -143,9 +144,9 @@ data Success
     deriving (Show, Eq)
 
 newtype Resp = Resp {
-      getResp :: Either VolatileDBError Success
+      getResp :: Either (VolatileDBError Block) Success
     }
-  deriving (Eq, Show)
+    deriving (Eq, Show)
```
Comment (mrBliss) [inline ouroboros-consensus-test/test-storage/Test/Ouroboros/Storage/VolatileDB/StateMachine.hs:149]: Two spaces

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs [hunk 22]
```diff
@@ -1,13 +1,19 @@
...
 
+import           Data.Proxy (Proxy)
 import           Data.Time.Clock (DiffTime)
+import           Data.Typeable (Typeable)
 
 import           Control.Monad.Class.MonadAsync (ExceptionInLinkedThread (..))
 
 import           Ouroboros.Network.ErrorPolicy
 
+import           Ouroboros.Consensus.Block (StandardHash)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs:16]: Convention: separate this import from the ones below.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs [hunk 23]
```diff
@@ -27,8 +33,8 @@ import           Ouroboros.Consensus.Util.ResourceRegistry
                      (RegistryClosedException, ResourceRegistryThreadException,
                      TempRegistryException)
 
-consensusErrorPolicy :: ErrorPolicies
-consensusErrorPolicy = ErrorPolicies {
+consensusErrorPolicy :: forall blk. (Typeable blk, StandardHash blk) => Proxy blk -> ErrorPolicies
+consensusErrorPolicy blki = ErrorPolicies {
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs:37]:
```suggestion
consensusErrorPolicy pb = ErrorPolicies {
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs [hunk 24]
```diff
@@ -1,13 +1,19 @@
-{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE PartialTypeSignatures #-}
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs:1]: As much as I appreciate this extension (and its author :wink:), it's not needed here.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs [hunk 25]
```diff
@@ -111,47 +111,47 @@ newtype ChainDbHandle m blk = CDBHandle (StrictTVar m (ChainDbState m blk))
 
 -- | Check if the ChainDB is open, if so, executing the given function on the
 -- 'ChainDbEnv', otherwise, throw a 'CloseDBError'.
-getEnv :: forall m blk r. (IOLike m, HasCallStack)
+getEnv :: forall m blk r. (IOLike m, HasCallStack, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Types.hs:114]: In this file I would also go for the shorter:
```suggestion
getEnv :: forall m blk r. (IOLike m, HasCallStack, HasHeader blk)
```
Many other functions in this file mention the same constraints.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs [hunk 26]
```diff
@@ -292,7 +293,7 @@ copyAndSnapshotRunner cdb@CDB{..} gcSchedule replayed =
 -- | Write a snapshot of the LedgerDB to disk and remove old snapshots
 -- (typically one) so that only 'onDiskNumSnapshots' snapshots are on disk.
 updateLedgerSnapshots
-  :: (IOLike m, LgrDbSerialiseConstraints blk)
+  :: (IOLike m, LgrDbSerialiseConstraints blk, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/Background.hs:296]:
```suggestion
  :: (IOLike m, LgrDbSerialiseConstraints blk, HasHeader blk)
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/API.hs [hunk 27]
```diff
@@ -343,12 +341,12 @@ data ApiMisuse =
     -- the database is closed.
   | OpenDBError
 
-deriving instance Show ApiMisuse
+deriving instance (StandardHash blk, Typeable blk) => Show (ApiMisuse blk)
 
-throwApiMisuse :: (MonadThrow m, HasCallStack) => ApiMisuse -> m a
+throwApiMisuse :: (MonadThrow m, HasCallStack, StandardHash blk, Typeable blk) => ApiMisuse blk -> m a
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/API.hs:346]: I think we can go for `HasHeader` in this file too.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/API.hs [hunk 28]
```diff
@@ -303,16 +303,16 @@ instance Ord (CompareTip blk) where
 -------------------------------------------------------------------------------}
 
 -- | Errors that might arise when working with this database.
-data ImmutableDBError
-  = ApiMisuse ApiMisuse PrettyCallStack
+data ImmutableDBError blk
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/API.hs:306]: Remove the `ExistentialQuantification` pragma from this file, as it should not be needed anymore.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Cache.hs [hunk 29]
```diff
@@ -769,13 +771,13 @@ readEntries cacheEnv chunk toRead =
     -- We don't know which of the two things happened, but the former is more
     -- likely, so we mention that file in the error message.
     noEntry :: SecondaryOffset -> m a
-    noEntry secondaryOffset = throwUnexpectedFailure $ InvalidFileError
+    noEntry secondaryOffset = (throwUnexpectedFailure :: UnexpectedFailure blk -> m a) $ InvalidFileError
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Cache.hs:774]:
```suggestion
    noEntry secondaryOffset = throwUnexpectedFailure $ InvalidFileError @blk
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs [hunk 30]
```diff
@@ -164,16 +165,19 @@ data BlockInfo blk = BlockInfo {
...
 -- | Errors which might arise when working with this database.
-data VolatileDBError =
-    -- | An error thrown because of incorrect usage of the VolatileDB
-    -- by the user.
+data VolatileDBError blk =
+
     ApiMisuse ApiMisuse
+    -- ^ An error thrown because of incorrect usage of the VolatileDB
+    -- by the user.
+
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs:173]: We prefer the previous style (comment before constructor) for sum types. (Also, mixing two styles in data type is rather inconsistent).

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs [hunk 31]
```diff
@@ -182,33 +186,30 @@ instance Exception VolatileDBError where
...
+newtype ApiMisuse =
     -- | The VolatileDB was closed. In case it was automatically closed
     -- because an unexpected error was thrown during a read operation or any
     -- exception was thrown during a write operation, that exception is
     -- embedded.
     ClosedDBError (Maybe SomeException)
   deriving (Show)
 
-data UnexpectedFailure =
+data UnexpectedFailure blk = (Typeable blk, StandardHash blk) =>
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs:197]: Remove the `ExistentialQuantification` from this file too.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs [hunk 32]
```diff
@@ -414,6 +417,7 @@ mkOpenStateHelper ccfg hasFS checkIntegrity validationPolicy tracer maxBlocksPer
       whenJust mErr' $ \(e, offset) ->
         truncateError file e offset
 
+
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs:420]: Not needed

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs [hunk 33]
```diff
@@ -22,15 +23,20 @@ import           Data.Bifunctor (first)
...
 import           Data.Map.Strict (Map)
 import qualified Data.Map.Strict as Map
+import           Data.Proxy (Proxy (..))
 import           Data.Set (Set)
 import qualified Data.Set as Set
 import           Data.Text (Text)
 import qualified Data.Text as T
 import           Text.Read (readMaybe)
 
+import           Cardano.Prelude (Typeable)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs:33]: Import it from `Data.Typeable`, we'd like to drop the dependency on `cardano-prelude` in the future.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs [hunk 34]
```diff
@@ -73,8 +79,11 @@ filePath fd = mkFsPath ["blocks-" ++ show fd ++ ".dat"]
   Exception handling
 ------------------------------------------------------------------------------}
 
-wrapFsError :: MonadCatch m => m a -> m a
-wrapFsError = handle $ throwIO . UnexpectedFailure . FileSystemError
+wrapFsError :: forall m0 a blk. (MonadCatch m0, StandardHash blk, Typeable blk) =>
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs:82]: Use `m` instead of `m0`

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs [hunk 35]
```diff
@@ -73,8 +79,11 @@ filePath fd = mkFsPath ["blocks-" ++ show fd ++ ".dat"]
...
+     Proxy blk
+  -> m0 a
+  -> m0 a
+wrapFsError _ = handle $ throwIO . (UnexpectedFailure  :: UnexpectedFailure blk -> VolatileDBError blk) . FileSystemError
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs:86]:
```suggestion
wrapFsError _ = handle $ throwIO . UnexpectedFailure @blk . FileSystemError
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl.hs [hunk 36]
```diff
@@ -297,7 +298,7 @@ closeDBImpl ImmutableDBEnv { hasFS, tracer, varInternalState } = do
         traceWith tracer DBClosed
 
 deleteAfterImpl ::
-     forall m blk. (HasCallStack, ConvertRawHash blk, IOLike m)
+     forall m blk. (HasCallStack, ConvertRawHash blk, IOLike m, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl.hs:301]:
```suggestion
     forall m blk. (HasCallStack, ConvertRawHash blk, IOLike m, HasHeader blk)
```

**Review by mrBliss — CHANGES_REQUESTED** [review]
This is looking very good! Indeed, it is not strictly needed to add a `blk` type argument to `ErrorPolicy` :+1: 

A bunch of small comments, mostly about using `HasHeader`, too long lines, naming of proxy arguments, the use of `TypeApplications` instead of signatures, etc.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs (hunk 32 above)
Comment (jutaro) [reply ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs:420]: Not sure about this!

**Comment by mrBliss** [comment]
Can you please replace all expression signatures you added to error types (to fix the ambiguous `blk` type parameter) with type applications? I commented on a few of them in my initial review but not on *all* of them :slightly_smiling_face:

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs [hunk 37]
```diff
@@ -156,7 +157,7 @@ data BlockSize
 -- | Read the entry at the given 'SecondaryOffset'. Interpret it as an EBB
 -- depending on the given 'IsEBB'.
 readEntry
-  :: forall m blk h. (HasCallStack, ConvertRawHash blk, MonadThrow m)
+  :: forall m blk h. (HasCallStack, ConvertRawHash blk, MonadThrow m, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs:160]: This line is too long, switch to the style mentioned above.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs [hunk 38]
```diff
@@ -172,7 +173,7 @@ readEntry hasFS chunk isEBB slotOffset = runIdentity <$>
 -- secondary index file.
 readEntries
   :: forall m blk h t.
-     (HasCallStack, ConvertRawHash blk, MonadThrow m, Traversable t)
+     (HasCallStack, ConvertRawHash blk, MonadThrow m, Traversable t, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs:176]: This line is too long, switch to the style mentioned above.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs [hunk 39]
```diff
@@ -212,7 +213,7 @@ readEntries hasFS chunk toRead =
 -- file is reached. The entry for which the stop condition is true will be the
 -- last in the returned list of entries.
 readAllEntries
-  :: forall m blk h. (HasCallStack, ConvertRawHash blk, MonadThrow m)
+  :: forall m blk h. (HasCallStack, ConvertRawHash blk, MonadThrow m, StandardHash blk, Typeable blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Index/Secondary.hs:216]: This line is too long, switch to the style mentioned above.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs [hunk 40]
```diff
@@ -184,19 +187,19 @@ type ModifyOpenState m blk h =
...
-    wrapFsError $ modifyWithTempRegistry getSt putSt (modSt hasFS)
+    wrapFsError (Proxy @blk) $ modifyWithTempRegistry getSt putSt (modSt hasFS)
   where
     getSt :: m (OpenState m blk h)
     getSt = mask_ $ takeMVar varInternalState >>= \case
       DbOpen ost -> return ost
       DbClosed   -> do
         putMVar varInternalState DbClosed
-        throwApiMisuse ClosedDBError
+        throwApiMisuse (ClosedDBError @blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs:202]:
```suggestion
        throwApiMisuse $ ClosedDBError @blk
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs [hunk 41]
```diff
@@ -219,10 +222,9 @@ modifyOpenState ImmutableDBEnv { hasFS = hasFS :: HasFS m h, .. } modSt =
           -- down the node anway, so it is safe to close the ImmutableDB here.
           ExitCaseAbort         -> DbClosed
           ExitCaseException ex
-            | Just (ApiMisuse {}) <- fromException ex
-            -> DbOpen ost
-            | otherwise
-            -> DbClosed
+            | Just ApiMisuse {} <- (fromException ex :: Maybe (ImmutableDBError blk))
+                                -> DbOpen ost
+            | otherwise         -> DbClosed
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs:227]:
```suggestion
            -> DbOpen ost
            | otherwise         
            -> DbClosed
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs [hunk 42]
```diff
@@ -249,13 +251,13 @@ withOpenState ImmutableDBEnv { hasFS = hasFS :: HasFS m h, .. } action = do
     open :: m (OpenState m blk h)
     open = atomically (readMVarSTM varInternalState) >>= \case
       DbOpen ost -> return ost
-      DbClosed   -> throwApiMisuse ClosedDBError
+      DbClosed   -> throwApiMisuse (ClosedDBError :: ApiMisuse blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/State.hs:254]:
```suggestion
      DbClosed   -> throwApiMisuse $ ClosedDBError @blk
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 43]
```diff
@@ -109,8 +112,11 @@ removeFilesStartingFrom HasFS { removeFile, listDirectory } chunk = do
       removeFile (fsPathSecondaryIndexFile i)
 
 -- | Rewrap 'FsError' in a 'ImmutableDBError'.
-wrapFsError :: MonadCatch m => m a -> m a
-wrapFsError = handle $ throwUnexpectedFailure . FileSystemError
+wrapFsError :: forall blk m a. (MonadCatch m, StandardHash blk, Typeable blk) =>
+     Proxy blk
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:116]:
```suggestion
wrapFsError ::
     forall blk m a. (MonadCatch m, StandardHash blk, Typeable blk)
  => Proxy blk
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 44]
```diff
@@ -109,8 +112,11 @@ removeFilesStartingFrom HasFS { removeFile, listDirectory } chunk = do
...
+  -> m a
+  -> m a
+wrapFsError _ = handle $ (throwUnexpectedFailure :: UnexpectedFailure blk -> m a) . FileSystemError
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:119]:
```suggestion
wrapFsError _ = handle $ throwUnexpectedFailure @blk . FileSystemError
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 45]
```diff
@@ -119,38 +125,43 @@ wrapFsError = handle $ throwUnexpectedFailure . FileSystemError
 -- This should be used whenever you want to run an action on the ImmutableDB
 -- and catch the 'ImmutableDBError' and the 'FsError' (wrapped in the former)
 -- it may thrown.
-tryImmutableDB :: MonadCatch m => m a -> m (Either ImmutableDBError a)
-tryImmutableDB = try . wrapFsError
+tryImmutableDB :: forall m blk a.(MonadCatch m, StandardHash blk, Typeable blk) =>
+     Proxy blk
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:129]:
```suggestion
tryImmutableDB ::
     forall m blk a. (MonadCatch m, StandardHash blk, Typeable blk)
  => Proxy blk
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 46]
```diff
@@ -119,38 +125,43 @@ wrapFsError = handle $ throwUnexpectedFailure . FileSystemError
...
   -> Lazy.ByteString
   -> m a
-runGet file get bl = case Get.runGetOrFail get bl of
+runGet _ file get bl = case Get.runGetOrFail get bl of
     Right (unconsumed, _, primary)
       | Lazy.null unconsumed
       -> return primary
       | otherwise
-      -> throwUnexpectedFailure $ InvalidFileError file "left-over bytes" prettyCallStack
+      -> throwUnexpectedFailure (InvalidFileError @blk file "left-over bytes" prettyCallStack )
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:148]:
```suggestion
      -> throwUnexpectedFailure $ InvalidFileError @blk file "left-over bytes" prettyCallStack
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 47]
```diff
@@ -119,38 +125,43 @@ wrapFsError = handle $ throwUnexpectedFailure . FileSystemError
...
     Left (_, _, msg)
-      -> throwUnexpectedFailure $ InvalidFileError file msg prettyCallStack
+      -> throwUnexpectedFailure (InvalidFileError @blk file msg prettyCallStack)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:150]:
```suggestion
      -> throwUnexpectedFailure $ InvalidFileError @blk file msg prettyCallStack
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs [hunk 48]
```diff
@@ -119,38 +125,43 @@ wrapFsError = handle $ throwUnexpectedFailure . FileSystemError
...
   -> Get a
   -> Lazy.ByteString
   -> m (Lazy.ByteString, a)
-runGetWithUnconsumed file get bl = case Get.runGetOrFail get bl of
+runGetWithUnconsumed _ file get bl = case Get.runGetOrFail get bl of
     Right (unconsumed, _, primary)
       -> return (unconsumed, primary)
     Left (_, _, msg)
-      -> throwUnexpectedFailure $ InvalidFileError file msg prettyCallStack
+      -> throwUnexpectedFailure (InvalidFileError @blk file msg prettyCallStack)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ImmutableDB/Impl/Util.hs:164]:
```suggestion
      -> throwUnexpectedFailure $ InvalidFileError @blk file msg prettyCallStack
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs [hunk 49]
```diff
@@ -231,14 +232,14 @@ openDB VolatileDbArgs { volHasFS = SomeHasFS hasFS, .. } = runWithTempRegistry $
   VolatileDB API
 ------------------------------------------------------------------------------}
 
-closeDBImpl :: IOLike m => VolatileDBEnv m blk -> m ()
+closeDBImpl :: forall m blk. (IOLike m, StandardHash blk, Typeable blk) => VolatileDBEnv m blk -> m ()
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs:235]:
```suggestion
closeDBImpl ::
     forall m blk. (IOLike m, StandardHash blk, Typeable blk)
  => VolatileDBEnv m blk
  -> m ()
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs [hunk 50]
```diff
@@ -514,7 +515,7 @@ getBlockInfoImpl = getterSTM $ \st hash ->
     ibiBlockInfo <$> Map.lookup hash (currentRevMap st)
 
 getMaxSlotNoImpl ::
-     forall m blockId. IOLike m
+     forall m blockId. (IOLike m, Typeable blockId, StandardHash blockId)
   => VolatileDBEnv m blockId
   -> STM m MaxSlotNo
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs:520]: Unrelated to this PR, `blockId` should be `blk` (forgotten in a past refactoring), but if we're touching this signature anyway, we should fix it:

```suggestion
     forall m blk. (IOLike m, Typeable blk, StandardHash blk)
  => VolatileDBEnv m blk
  -> STM m MaxSlotNo
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs (hunk 49 above)
Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs:235]: Also almost all functions in this module use `HasHeader blk`, so use that instead of the more verbose `StandardHash blk, Typeable blk`.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs [hunk 51]
```diff
@@ -551,12 +552,12 @@ nextFile hasFS = do
...
-     forall m blk a. IOLike m
+     forall m blk a. (IOLike m, StandardHash blk, Typeable blk)
   => (forall h. OpenState blk h -> a)
   -> VolatileDBEnv m blk
   -> STM m a
 getterSTM fromSt VolatileDBEnv { varInternalState } = do
     mSt <- RAWLock.read varInternalState
     case mSt of
-      DbClosed  -> throwIO $ ApiMisuse $ ClosedDBError Nothing
+      DbClosed  -> throwIO (ApiMisuse (ClosedDBError Nothing) :: VolatileDBError blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs:562]:
```suggestion
      DbClosed  -> throwIO $ ApiMisuse $ ClosedDBError @blk Nothing
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs [hunk 52]
```diff
@@ -182,33 +183,30 @@ instance Exception VolatileDBError where
...
 
     -- | Block missing
     --
     -- This exception gets thrown when a block that we /know/ it should be in
     -- the VolatileDB, nonetheless was not found.
     --
     -- This exception will be thrown by @getKnownBlockComponent@.
-  | forall blk. (Typeable blk, StandardHash blk) =>
-      MissingBlockError (Proxy blk) (HeaderHash blk)
+  | MissingBlockError (Proxy blk) (HeaderHash blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs:209]: If the `Proxy` can be dropped with `AllowAmbiguousTypes`, then it should be.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs [hunk 53]
```diff
@@ -219,10 +217,9 @@ data UnexpectedFailure =
     -- VolatileDB. While this exception typically means the block has been
     -- corrupted, it could also mean the block didn't pass the check at the time
     -- it was added.
-  | forall blk. (Typeable blk, StandardHash blk) =>
-      CorruptBlockError (Proxy blk) (HeaderHash blk)
+  | CorruptBlockError (Proxy blk) (HeaderHash blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/API.hs:220]: If the `Proxy` can be dropped with `AllowAmbiguousTypes`, then it should be.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs [hunk 54]
```diff
@@ -276,8 +279,8 @@ withOpenState VolatileDBEnv {hasFS = hasFS :: HasFS m h, varInternalState} actio
           ExitCaseException _ex                            -> Nothing
           ExitCaseSuccess (Right _)                        -> Nothing
           -- In case of a VolatileDBError, close when unexpected
-          ExitCaseSuccess (Left ex@(UnexpectedFailure {})) -> Just (toException ex)
-          ExitCaseSuccess (Left (ApiMisuse {}))            -> Nothing
+          ExitCaseSuccess (Left ex@UnexpectedFailure {}) -> Just (toException ex)
+          ExitCaseSuccess (Left ApiMisuse {})            -> Nothing
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs:283]: Keep these two cases aligned with the three above it.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs (hunk 32 above)
Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs:420]: As said on Slack, this extra blank line is indeed not needed :slightly_smiling_face:

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs [hunk 55]
```diff
@@ -252,9 +255,9 @@ withOpenState VolatileDBEnv {hasFS = hasFS :: HasFS m h, varInternalState} actio
             -- caused it is thrown.
             mbCurState <-
               RAWLock.poison varInternalState $ \_st ->
-                ApiMisuse (ClosedDBError (Just ex))
+                ApiMisuse (ClosedDBError (Just ex)) :: (VolatileDBError blk)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/State.hs:258]:
```suggestion
                ApiMisuse (ClosedDBError @blk (Just ex))
```

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs [hunk 56]
```diff
@@ -22,15 +24,19 @@ import           Data.Bifunctor (first)
...
 import qualified Data.Set as Set
 import           Data.Text (Text)
 import qualified Data.Text as T
+import           Data.Typeable (Typeable)
 import           Text.Read (readMaybe)
 
 import           Ouroboros.Consensus.Util (lastMaybe)
 import           Ouroboros.Consensus.Util.IOLike
 
+import           Ouroboros.Consensus.Block (StandardHash)
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs:38]: Can be grouped together with the two imports above it.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs [hunk 57]
```diff
@@ -73,8 +79,11 @@ filePath fd = mkFsPath ["blocks-" ++ show fd ++ ".dat"]
   Exception handling
 ------------------------------------------------------------------------------}
 
-wrapFsError :: MonadCatch m => m a -> m a
-wrapFsError = handle $ throwIO . UnexpectedFailure . FileSystemError
+wrapFsError :: forall m a blk. (MonadCatch m, StandardHash blk, Typeable blk) =>
+     Proxy blk
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/VolatileDB/Impl/Util.hs:83]:
```suggestion
wrapFsError ::
     forall m a blk. (MonadCatch m, StandardHash blk, Typeable blk)
  => Proxy blk
```

**Review by mrBliss — APPROVED** [review]

**Comment by mrBliss** [comment]
bors merge
