### PR TITLE
Error reporting for network & consensus errors

### LINKED ISSUE #4000: `RethrowPolicy` is not logging exceptions, unlike `ErrorPolicy`
The following error is not logged to the log file, but only shows in `stdout` (probably because of GHC top level error handler):

```
cardano-node: ExceptionInLinkedThread "ThreadId 47" (ApiMisuse (ClosedDBError (Just (FsError {fsErrorType = FsDeviceFull, fsErrorPath = /mnt/HC_Volume_17016868/cardano-node/blocks/volatile/blocks-7685.dat, fsErrorString = "No space left on device", fsErrorNo = Just (Errno 28), fsErrorStack = CallStack (from HasCallStack):
  prettyCallStack, called at src/Ouroboros/Consensus/Storage/FS/API/Types.hs:297:23 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.API.Types
  ioToFsError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:88:41 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.IO
  handleError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:84:23 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.IO
  rethrowFsError, called at src/Ouroboros/Consensus/Storage/FS/IO.hs:54:39 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.IO
  hPutSome, called at src/Ouroboros/Consensus/Storage/FS/API.hs:103:5 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.API
  hPutAllStrict, called at src/Ouroboros/Consensus/Storage/FS/API.hs:280:19 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.FS.API
  hPutAll, called at src/Ouroboros/Consensus/Storage/VolatileDB/Impl.hs:366:39 in ouroboros-consensus-0.1.0.0-3e0c35ca6cdc55ae943ecbdd5636e68d9b1f1e912253d8a7ff6d1af1a76dd0d5:Ouroboros.Consensus.Storage.VolatileDB.Impl, fsLimitation = False}))))
```

The node is configured with `EnabledP2P: true`.

`RethrowPolicy` are different in that matter to `ErrorPolicies`.  The former don't log exceptions, while the latter do.

We can either:

* declare that `RethrowPolicy` should not log exceptions as this will duplicate error messages in many cases. For example exceptions thrown by any mini-protocol are logged by `ConnectionHandlerTracer` (which is part of `ConnectionManagerTracer`).  Thanks to that `runRethrowPolicy` is a pure function.
* make `runRethrowPolicy` an effectuful function, which log exceptions.

The advantage of the latter approach is that:
* we don't miss errors like the above (which is thrown not from a connection thread), but somewhere from consensus code which is using `RethrowPolicy` (this is also easy to fix on the consensus side)
* we have one tracer which logs all important errors. This can be turned on by default (or not even configurable!).

### PR DESCRIPTION
**Pull request by coot**
# Description

`runRethrowPolicy` logs the exception through a separate tracer:
`RethrowPolicyTracer`.  A seprate tracer will allow to not use a configuration
to disable it in `cardano-node`.

Also added a top level handler for exceptions thrown by the consensus code.
This tracer should also not be configurable.  To avoid duplication it does not
log diiffusion startup failure exceptions and exceptions that were rethrown
from connection handler thread (which are wrapped in `ExceptionInHandler`).

Fixes #4000.

- rethrow-policies: fixed typos
- rethrow-policies: added RethrowPolicyTracer
- connection-handler: rethrow exceptions using ExceptionInHandler
- ouroboros-consensus: updated consensusRethrowPolicy
- ouroboros-newtork-framework: changed ExceptionInHandler
- ouroboros-consensus: added top level error tracer

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]
LGTM :)

File: ouroboros-consensus/src/Ouroboros/Consensus/Node.hs [hunk 1]
```diff
@@ -277,89 +277,99 @@ run args stdArgs = stdLowLevelRunNodeArgsIO args stdArgs >>= runWith args
...
-                                      (miniProtocolParameters nodeKernelArgs)
-                                      ntnApps
-                                      ntcApps
-                                      nodeKernel
-                                      peerMetrics
-
-        llrnRunDataDiffusion registry apps appsExtra
+    withRegistry $ \registry ->
+      handleJust
+             -- ignore exception thrown in connection handlers and diffusion
```
[the remark this answers is not in the document]
Comment (coot) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node.hs:290]: They are already logged by the network layer.  I'll update the comment.

File: ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs [hunk 2]
```diff
@@ -70,9 +79,9 @@ instance Monoid ErrorCommand where
     mempty = ShutdownPeer
 
 
--- | Whether an exception happend on outbound or inbound connection.
+-- | Whether an exception happened on outbound or inbound connection.
 --
--- TODO: It would be more useful to have access whether the exception happend
+-- TODO: It would be more useful to have access whether the exception happened
```
Comment (dnadales) [inline ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs:84]:
```suggestion
-- TODO: It would be more useful to have access to whether the exception happened
```

File: ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs [hunk 3]
```diff
@@ -86,12 +95,32 @@ data ErrorContext = OutboundError
 type RethrowPolicy_ = ErrorContext -> SomeException -> ErrorCommand
 
 newtype RethrowPolicy = RethrowPolicy {
-    runRethrowPolicy :: RethrowPolicy_
+    runRethrowPolicyPure :: RethrowPolicy_
```
Comment (dnadales) [inline ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs:98]: Why the `Pure` suffix?

File: ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs (hunk 2 above)
Comment (coot) [reply ouroboros-network-framework/src/Ouroboros/Network/RethrowPolicy.hs:84]: Merged.

**Comment by coot** [comment]
@bolt12 I added a commit which ignores `ExceptionInHandler` in top level `Diffusion.InitializationTracer`.

**Comment by coot** [comment]
Hmm, I think this PR should be changed.  Parts of it are inferior to what we already have, let me try to explain.

The diffusion already has a top level handler which logs all exceptions (the only confusing part about it is that the tracer is called `InitializationTracer`).  If we introduce `RethrowPolicyTracer` we cannot distinguish errors thrown by connection handler which should kill the node (which ought to use `Alert` severity) from ones that just should kill the connection (which ought to have `Info` severity).

For this reason I will remove the part that introduced `RethrowPolicyTracer`.

**Comment by coot** [comment]
bors merge
