### PR TITLE
ChainDB.Iterator: fix EBB bug

### LINKED ISSUE #1435: test-consensus divergence: Two RealPBFT nodes exchange two BlockFetch messages forever
On master, this test case diverges.

```
      let ncn = NumCoreNodes 4 in
      prop_simple_real_pbft_convergence (SecurityParam 5) TestConfig
        { numCoreNodes = ncn
        , numSlots     = NumSlots 58
        , nodeJoinPlan = NodeJoinPlan $ Map.fromList [(CoreNodeId 0,SlotNo 3),(CoreNodeId 1,SlotNo 3),(CoreNodeId 2,SlotNo 5),(CoreNodeId 3,SlotNo 57)]
        , nodeTopology = meshNodeTopology ncn
        , slotLengths  = defaultSlotLengths
        , initSeed     = Seed (11044330969750026700,14522662956180538128,9026549867550077426,3049168255170604478,643621447671665184)
        }
```

I've observed this behavior as early as commit 8e0cab4f (merge PR 1402). I haven't yet checked when this behavior originated.

During slot 57, the two nodes indefinitely exchange two BlockFetch messages, `MsgRequestRange` and `MsgNoBlocks`. In the `io-sim` monad, this locks up the entire test.

```
$ cabal v2-run ouroboros-consensus:test:test-consensus
...
Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Recv CoreId 3 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Send CoreId 3 MsgNoBlocks
Recv CoreId 0 MsgNoBlocks
Send CoreId 0 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Recv CoreId 3 MsgRequestRange ChainRange (At (Block {blockPointSlot = SlotNo {unSlotNo = 49}, blockPointHash = ByronHash {unByronHash = AbstractHash f89fba07311a080c9fafeb6318329373bba188a93acff8b3d6d9a6262df0b521}})) (At (Block {blockPointSlot = SlotNo {unSlotNo = 50}, blockPointHash = ByronHash {unByronHash = AbstractHash 4c35e8707e0588957598620e5e902448c9b947d9fd6ffebe470dbf4a639c07b9}}))
Send CoreId 3 MsgNoBlocks
Recv CoreId 0 MsgNoBlocks
... ad infinitum ...
```

This Issue is to debug and fix this divergence. I'm unsure how this would manifest in `IO` as opposed to `io-sim`. Perhaps it's just adding unnecessary load on the network and compute (and log?). But since `io-sim` diverges, this causes the `test-consensus` to diverge, which is inconvenient.

### PR DESCRIPTION
**Pull request by mrBliss**
Closes #1435.

See the comment for more information.

### CODE REVIEW

**Comment by mrBliss** [comment]
Many thanks to @nfrisby for providing such a [detailed bug report](https://github.com/input-output-hk/ouroboros-network/issues/1435#issuecomment-575647697)!

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs [hunk 1]
```diff
@@ -257,24 +258,49 @@ newIterator itEnv@IteratorEnv{..} getItEnv registry from to = do
...
+             --    ImmutableDB.
+             --
+             -- 2. The end point is the EBB with the same slot number as the
+             --    regular block which is currently at the tip of the
+             --    ImmutableDB. In this case, we can stream from just the
+             --    ImmutableDB, as the end point is in the ImmutableDB.
+             --
+             -- 3. The fork is too old, i.e., the end point refers to a block
+             --    (or EBB) not on the current chain, but with the same slot
+             --    number as our tip.
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs]: If I understand correctly, I think it would be clearer to explicitly state here that Case 3 should always raise the `ForkTooOld` exception.

(I'm not certain I understand correctly, because I'm not certain what exactly you mean by "current chain" here: if the ImmDB tip is an EBB U, it's possible that multiple proper blocks V, V', V'', ... with the same slot as U are in the VolDB and we should be able to open an iterator for any of them, regardless of which one is on the "current(ly selected) chain", right?)

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs [hunk 2]
```diff
@@ -257,24 +258,49 @@ newIterator itEnv@IteratorEnv{..} getItEnv registry from to = do
...
+             --
+             -- We don't know upfront with which of the three cases we're
+             -- dealing, as we don't know which block the end point refers to
+             -- without trying to read it from the ImmutableDB or VolatileDB.
+             -- The important thing is to also try the ImmutableDB in case 2.
+             | IsEBB <- tipIsEBB  -- Case 1 or 3
              -> findPathInVolDB
+             | otherwise  -- Case 2 or 3
+             -> streamFromImmDB `fallbackTo` findPathInVolDB
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs]: Related to my comment on Case 3 above: when do we need to fall back onto `findPathInVolDB` here?

We reach this alternative when the end point and the tip have the same slot, they also have differing hashes, and the tip is not an EBB. So isn't Case 2 (covered by `streamFromImmDB`) the only possibility that should _not_ raise a `ForkTooOld` exception?

**Comment by mrBliss** [comment]
You're right. I have rewritten the logic and made all 6 cases explicit (in the tests too). There was indeed no fallback to the VolatileDB needed.

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs (hunk 1 above)
Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs]: New comment is great.

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs (hunk 2 above)
Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs]: 👍

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/Iterator.hs]: New code looks great.
