### PR TITLE
BlockFetch: wait until the block has been written to disk

### LINKED ISSUE #1845: Refine the BF logic for updating the PeerFetchState with async block adds
While developing a new approach to the `ThreadNet` tests, I noticed something unexpected in the BlockFetch threads' `Tracer` output.

As of PR #1709, the BF client adds blocks to CDB asynchronously instead of synchronously. Since the `addFetchedBlock` call in the BF client now returns immediately, the BF client now updates its `PeerFetchStatus` (to indicate the fetched block is no-longer in flight) before the CDB updates its current chain (to include the new fetched block) (or is it `ChainDB.getIsFetched` and not the current chain?).

As a result I'm seeing the node's BF fetch logic thread immediately add a duplicate fetch request for the same block. Once the BF client updates its peer status, the relevant inputs to the fetch logic thread now look the same as they did before it originally made the fetch request: the (fetched) block is not in flight and it is not in the CDB's current chain -- it's about to be, but the fetch logic doesn't know that.

This is causing the BF client in the `ThreadNet` to fetch every (?) block twice. This Issue is resolved when the the BF client no longer causes the node's fetch logic thread to repeat its requests.

@duncan shared some thoughts here https://input-output-rnd.slack.com/archives/GCW2S19CM/p1585076440303700

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1845.

### CODE REVIEW

**Comment by mrBliss** [comment]
Alternatively, we also wait until the block has been processed by chain selection, which means we don't need the first commit. In that case, the use of `addBlockWaitWrittenToDisk` in the second commit should be replaced with `addBlock`. Also see #1015.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs [hunk 1]
```diff
@@ -251,18 +252,19 @@ addBlockSync cdb@CDB {..} BlockToAdd { blockToAdd = b, .. } = do
         VolDB.putBlock cdbVolDB b
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs]: This alternative currently delivers the `WrittenToDisk` promise after chain selection, whereas it could deliver it before. Is there a reason to favor one option over the other? "Promptness" of written-to-disk would favor changing this.

Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs]: This alternative currently delivers the `WrittenToDisk` promise after chain selection, whereas it could deliver it before. Is there a reason to favor one option over the other? "Promptness" of written-to-disk would favor changing this.

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/Impl/ChainSel.hs]: You're totally right, I glossed over it. I'll fix it.

File: ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/API.hs [hunk 2]
```diff
@@ -332,7 +333,20 @@ instance DB (ChainDB m blk) where
 -------------------------------------------------------------------------------}
 
 data AddBlockPromise m blk = AddBlockPromise
-    { blockProcessed          :: STM m (Point blk)
+    { blockWrittenToDisk      :: STM m Bool
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/API.hs]: One other minor comment: you've organized the new promise around "written to disk". Based on the code I'm seeing, it looks like "added to VolDB" would also be accurate. Just pointing that out, in case the less-specific name is appealing.

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Storage/ChainDB/API.hs]: I take your point. But IMO "written to disk" is fine.

**Comment by mrBliss** [comment]
@nfrisby Could you verify that this actually fixes #1845 (maybe you have already)? I expect it does, but I haven't verified it myself.

**Comment by nfrisby** [comment]
@mrBliss Yes, it does what we expected. Basic test use two nodes, trace the BlockFetch client and BlockFetch decision for one node, inspect the output. Here's the diff in that output that I see by applying your fix.

```
10,17c10
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Right [At (Block {blockPointSlot = SlotNo {unSlotN
< TraceLabelPeer (CoreId (CoreNodeId 2)) (AddedFetchRequest (FetchRequest {fetchRequestFragme
< TraceLabelPeer (CoreId (CoreNodeId 2)) (CompletedFetchBatch (ChainRange (At (Block {blockPo
< TraceLabelPeer (CoreId (CoreNodeId 2)) (AcknowledgedFetchRequest (FetchRequest {fetchReques
< TraceLabelPeer (CoreId (CoreNodeId 2)) (StartedFetchBatch (ChainRange (At (Block {blockPoin
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
< TraceLabelPeer (CoreId (CoreNodeId 2)) (CompletedBlockFetch (At (Block {blockPointSlot = Sl
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
---
> [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineAlreadyFetched)]
18a12
> [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineAlreadyFetched)]
25,33c19
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Right [At (Block {blockPointSlot = SlotNo {unSlotN
< TraceLabelPeer (CoreId (CoreNodeId 2)) (AddedFetchRequest (FetchRequest {fetchRequestFragme
< TraceLabelPeer (CoreId (CoreNodeId 2)) (CompletedFetchBatch (ChainRange (At (Block {blockPo
< TraceLabelPeer (CoreId (CoreNodeId 2)) (AcknowledgedFetchRequest (FetchRequest {fetchReques
< TraceLabelPeer (CoreId (CoreNodeId 2)) (StartedFetchBatch (ChainRange (At (Block {blockPoin
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
< TraceLabelPeer (CoreId (CoreNodeId 2)) (CompletedBlockFetch (At (Block {blockPointSlot = Sl
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
< [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
---
> [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineAlreadyFetched)]
34a21,22
> [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineAlreadyFetched)]
> [TraceLabelPeer (CoreId (CoreNodeId 2)) (Left FetchDeclineChainNotPlausible)]
```

Crucial observation: there are less `AddedFetchRequest` events.

**Comment by mrBliss** [comment]
Thanks for verifying it!
