### PR TITLE
Extend Cardano ThreadNet tests so that Shelley era contains active stake pools

### LINKED ISSUE #2388: Introduce registered stakepools early in the Shelley era in Cardano ThreadNet tests
At the moment, the tests fail with a (de)centralization parameter of `d=0`, because at the moment, only the overlay slots of the Shelley era have leaders.

### PR DESCRIPTION
**Pull request by nfrisby**
Fixes #2388.

The big commit could be decomposed a little, but the excess diff I'm thinking of is mostly minor (whitespace/renaming/adding one param to `testGenTxs` etc) and localized -- it's obvious when you see it. Please ping me if the decomposition would be worthwhile by making your review that much easier.

cc: @edsko FYI

### CODE REVIEW

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs [hunk 1]
```diff
@@ -1,15 +1,308 @@
...
+        , SL._poolPubKey = Shelley.mkKeyHash poolSK
+        , SL._poolRAcnt  =
+            SL.RewardAcnt Shelley.networkId $ Shelley.mkCredential poolSK
+        , SL._poolRelays = StrictSeq.empty
+        , SL._poolVrf    = Shelley.mkKeyHashVrf vrfSK
+        }
+
+-----
+
+ejectShelleyNS :: NS f (CardanoEras c) -> Maybe (f (ShelleyBlock c))
```
Comment (nfrisby) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:286]: @mrBliss Are there pre-existing functions that replace/simplify these `ejectShelleyNS`, `ejectShelleyTickedLedgerState`, and `getUTxOShelley` functions I'm defining here?

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs [hunk 2]
```diff
@@ -36,3 +40,29 @@ instance HashAlgorithm h => Crypto (TPraosMockCrypto h) where
 instance HashAlgorithm h => TPraosCrypto (TPraosMockCrypto h)
 
 type Block h = ShelleyBlock (TPraosMockCrypto h)
+
+-- | Like 'TPraosMockCrypto' except mocks fewer components in order to be
```
Comment (nfrisby) [inline ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs:44]: Should this crypto bundle be relocated to `ouroboros-consensus-cardano/src/Test/*`? (That file hierarchy does not yet exist.)

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs [hunk 3]
```diff
@@ -36,3 +40,29 @@ instance HashAlgorithm h => Crypto (TPraosMockCrypto h) where
...
+-- generators from being used. Currently, this is not an obstacle for example
+-- in the Cardano ThreadNet tests.
+--
+-- NOTE: The "Ouroboros.Consensus.Cardano.CanHardFork" translation currently
+-- assumes that @ADDRHASH@ has the same bit size as Byron address hashes (ie
+-- 224); that's why we use 'Blake25_224' here.
+--
+-- NOTE: The @shelley-spec-ledger@ package currently requires that @'DSIGN' ~
+-- 'Ed25519DSIGN'.
+data TPraosMockCryptoCompatByron h
```
Comment (mrBliss) [inline ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs:57]: Some thoughts about parameterising mock crypto by `h` (also `TPraosMockCrypto`): in #2503, I rewrite the examples used by the golden tests to use `TPraosStandardCrypto`, so no more `TPraosMockCrypto` there. I believe the serialisation roundtrip tests still use `ShortHash` for performance reasons and for generator reuse/ease (IIRC). The Shelley ThreadNet tests also use `ShortHash` for performance. Any other things I'm missing? All other things uses Mock* with `Blake2b_256`, I suppose. So actually there's no need to parameterise `TPraosMockCryptoCompatByron` over `h`, correct? Nevertheless, I think it's fine to leave it as-is.

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs [hunk 4]
```diff
@@ -36,3 +40,29 @@ instance HashAlgorithm h => Crypto (TPraosMockCrypto h) where
...
+-- | Like 'TPraosMockCrypto' except mocks fewer components in order to be
+-- compatible with bootstrapping from Byron
+--
+-- Note that mocking less components does prevent the @cardano-ledger-specs@
+-- generators from being used. Currently, this is not an obstacle for example
+-- in the Cardano ThreadNet tests.
+--
+-- NOTE: The "Ouroboros.Consensus.Cardano.CanHardFork" translation currently
+-- assumes that @ADDRHASH@ has the same bit size as Byron address hashes (ie
+-- 224); that's why we use 'Blake25_224' here.
```
Comment (mrBliss) [inline ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs:53]:
```suggestion
-- 224); that's why we use 'Blake2b_224' here.
```

File: ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs [hunk 5]
```diff
@@ -107,6 +119,10 @@ data TestSetup = TestSetup
   , setupD                 :: Shelley.DecentralizationParam
   , setupHardFork          :: Bool
     -- ^ whether the proposal should trigger a hard fork or not
+  , setupInitialNonce      :: SL.Nonce
+    -- ^ the initial Shelley 'SL.ticknStateEpochNonce'
+    --
+    -- We vary it too ensure we explore different leader schedules.
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs:125]:
```suggestion
    -- We vary it to ensure we explore different leader schedules.
```

File: ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs [hunk 6]
```diff
@@ -530,20 +577,57 @@ prop_simple_cardano_convergence TestSetup
...
+        shift x = Set.mapMonotonic (Util.addSlots (unEpochSize x))
+
+        -- The relative offset of the overlay slots in each Shelley epoch.
+        overlayOffsets :: Set SlotNo
+        overlayOffsets =
+            Map.keysSet $
+            runIdentity $ flip runReaderT shelleyGlobals $
+            SL.overlaySchedule
+              @Crypto
+              (EpochNo 0)   -- Ignoring this input; see uses of @shift@ above
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs:618]: I don't understand, if you're shifting all slots by the epoch size, why not use `EpochNo 1` here?

Ah, you're shifting by `epochSizeByron` first. A cleaner solution would be to pass the correct `EpochInfo` to `shelleyGlobals`. You would have to construct a correct `Summary` and pass that to [`snapshotEpochInfo`](https://github.com/input-output-hk/ouroboros-network/blob/3a83c64ce76fb995b9557d3eb55d3c7e1c2fc251/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/EpochInfo.hs#L48).

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs [hunk 7]
```diff
@@ -1,15 +1,308 @@
...
+data CardanoTxGenExtra c = CardanoTxGenExtra
+  { ctgeByronGenesisKeys :: GeneratedSecrets
+  , ctgeNetworkMagic     :: Byron.NetworkMagic
+  , ctgeShelleyCoreNodes :: [Shelley.CoreNode c]
+  }
+
+instance ( TPraosCrypto c
+           -- These equalities allow use of Byron bootstrap addresses in the
+           -- Shelley era, since @shelley-spec-ledger@ requires Ed25519 and the
+           -- current Byron-to-Shelley translation requires _224.
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:77]:
```suggestion
           -- current Byron-to-Shelley translation requires Blake2b_224.
```
Or was the omission intentional?

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs [hunk 8]
```diff
@@ -1,15 +1,308 @@
...
+-- It returns 'Nothing' if the core node does not have any utxo in its
+-- 'byronAddr' (eg if this transaction has already been applied).
+migrateUTxO :: forall c.
+               (TPraosCrypto c, DSIGN c ~ Ed25519DSIGN)
+            => MigrationInfo c
+            -> SlotNo
+            -> LedgerConfig (CardanoBlock c)
+            -> LedgerState (CardanoBlock c)
+            -> Maybe (GenTx (CardanoBlock c))
+migrateUTxO migrationInfo curSlot lcfg lst
```
Comment (mrBliss) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:153]: I must say that I'm not that familiar with all this ledger business. Best to let @nc6 review this part.

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs (hunk 1 above)
Comment (mrBliss) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:286]: There's is the [`LedgerStateShelley`](https://github.com/input-output-hk/ouroboros-network/blob/3a83c64ce76fb995b9557d3eb55d3c7e1c2fc251/ouroboros-consensus-cardano/src/Ouroboros/Consensus/Cardano/Block.hs#L494) pattern synonym, but that's not for a *ticked* ledger state, and I don't want to add such a synonym as I don't want other packages to mess with ticked ledger states.

No, I don't think there are any pre-existing functions you can use to replace/simplify these three.

Why "eject"? Is that an existing naming convention? It makes me think of "reject", which would do the opposite (so in some sense, "eject" makes sense). I would go for something like "select" instead.

Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:286]: We agreed to follow https://hackage.haskell.org/package/generics-sop-0.5.1.0/docs/Generics-SOP.html#t:Ejection

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs (hunk 7 above)
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:77]: It was, but no need to be coy. Clarified, thanks!

File: ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs (hunk 5 above)
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs:125]: Fixed, thanks.

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs (hunk 4 above)
Comment (nfrisby) [reply ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs:53]: Fixed, thanks.

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs (hunk 3 above)
Comment (nfrisby) [reply ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs:57]: Yeah, `git grep -e 'TPraosMockCrypto' -- '*hs' | grep -vE -e "TPraosMockCrypto[')]" -e 'TPraosMockCrypto (h|ShortHash)'` confirms that your list is exhaustive for `TPraosMockCrypto`.

And this PR only uses the new `TPraosMockCryptoCompatByron` at type `Blake2b_256`.

But I agree the parameterization is fine as-is. Some constraint contexts would be simpler without it, but it's not burdensome to currently justify the extra diff now, in my opinion. In fact, some functions and certainly some types are clearer/safer when paramterized over `h`, in my opinion.

File: ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs (hunk 6 above)
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs:618]: We agreed that the `Summary` is not easy to create here, so to avoid inflating the diff eta, we compromised with a smaller refactor:

```
        -- The overlay slots in the ith Shelley epoch.
        overlayOffsets :: Word64 -> Set SlotNo
        overlayOffsets i =
            -- Shift to account for the initial Byron era.
            Set.mapMonotonic (Util.addSlots numByronSlots) $

            Map.keysSet $
            runIdentity $ flip runReaderT shelleyGlobals $
            SL.overlaySchedule
              @Crypto
              (EpochNo i)   -- NB 0 <-> the first /Shelley/ epoch
              genesisKeyHashes
              (sgProtocolParams genesisShelley)   -- notably contains setupD
```

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs (hunk 8 above)
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:153]: Yeah, that's what I had in mind when I added @nc6 as a reviewer: this part and then just a general FYI.

File: ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs (hunk 2 above)
Comment (nfrisby) [reply ouroboros-consensus-shelley-test/src/Test/Consensus/Shelley/MockCrypto.hs]: Done, thanks!

**Comment by nfrisby** [comment]
I force pushed updated commits: they now extend `origin/master` and reflect Thomas' comments.

I think it's ready for merge, as long as @nc6 doesn't see any problems/simplification opportunities in the transaction created in the new lines of `ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs`.

**Comment by nfrisby** [comment]
I rebased onto `origin/master` -- no conflicts, everything built locally 👍

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs [hunk 9]
```diff
@@ -1,15 +1,308 @@
...
+            pick (SL.TxOut addr _) =
+                addr == SL.AddrBootstrap (SL.BootstrapAddress byronAddr)
+
+        -- Total held by 'byronAddr'
+        pickedCoin :: SL.Coin
+        pickedCoin =
+            sum $ fmap (\(SL.TxOut _ coin) -> coin) picked
+
+        fee        :: SL.Coin
+        fee        = 0
```
Comment (nc6) [inline ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:169]: I guess you just have `minFee` and `poolDeposit` set to 0?

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+-- NOTE: The @shelley-spec-ledger@ package currently requires that @'DSIGN' ~
+-- 'Ed25519DSIGN'.
+data TPraosMockCryptoCompatByron h
+
+instance HashAlgorithm h => Crypto (TPraosMockCryptoCompatByron h) where
+  type ADDRHASH (TPraosMockCryptoCompatByron h) = Blake2b_224
+  type DSIGN    (TPraosMockCryptoCompatByron h) = Ed25519DSIGN
+  type HASH     (TPraosMockCryptoCompatByron h) = h
+  type KES      (TPraosMockCryptoCompatByron h) = MockKES 10
+  type VRF      (TPraosMockCryptoCompatByron h) = FakeVRF
```
[the remark this answers is not in the document]
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs:41]: Good to know, thanks. My general preference is to mock as much as possible. Is there a better alternative? Or maybe the real `VRF` is relatively simple and not worth mocking? I'm unfamiliar.

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+-- 'Test.Consensus.Shelley.MockCrypto.TPraosMockCrypto'. This prevents the
+-- @cardano-ledger-specs@ generators from being re-used. Currently, this is not
+-- an obstacle for example in the Cardano ThreadNet tests.
+--
+-- NOTE: The "Ouroboros.Consensus.Cardano.CanHardFork" translation currently
+-- assumes that @ADDRHASH@ has the same bit size as Byron address hashes (ie
+-- 224); that's why we use 'Blake2b_224' here.
+--
+-- NOTE: The @shelley-spec-ledger@ package currently requires that @'DSIGN' ~
+-- 'Ed25519DSIGN'.
```
[the remark this answers is not in the document]
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs:33]: Ah, my edits lost a key phrase: "in order to support Byron witnesses". I'll add it back.

For example: https://github.com/input-output-hk/cardano-ledger-specs/blob/dae9940d110d8671a154e5f9946195c315837905/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Address/Bootstrap.hs#L198-L202

File: ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs [hunk 12]
```diff
@@ -528,20 +577,56 @@ prop_simple_cardano_convergence TestSetup
...
+        takeWhile (isJust . Set.lookupLT (SlotNo t)) $
+        map overlayOffsets [0..]
+      where
+        NumSlots t = numSlots
+
+        -- The overlay slots in the ith Shelley epoch.
+        overlayOffsets :: Word64 -> Set SlotNo
+        overlayOffsets i =
+            -- Shift to account for the initial Byron era.
+            Set.mapMonotonic (Util.addSlots numByronSlots) $
```
[the remark this answers is not in the document]
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs:610]: Yep; it seemed quite a bit more direct this way instead of building a sophisticated `epochInfo` (by building a HardFork `Summary` eg).

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs [hunk 13]
```diff
@@ -1,15 +1,308 @@
...
+  , ctgeNetworkMagic     :: Byron.NetworkMagic
+  , ctgeShelleyCoreNodes :: [Shelley.CoreNode c]
+  }
+
+instance ( TPraosCrypto c
+           -- These equalities allow use of Byron bootstrap addresses in the
+           -- Shelley era, since @shelley-spec-ledger@ requires Ed25519 and the
+           -- current Byron-to-Shelley translation requires a 224-bit hash.
+         , ADDRHASH c ~ Blake2b_224
+         , DSIGN    c ~ Ed25519DSIGN
```
[the remark this answers is not in the document]
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:79]: (See other comment thread.)

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs (hunk 9 above)
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:169]: Yeah, the `Cardano` ThreadNet uses the `ouroboros-shelley-test` genesis config

https://github.com/input-output-hk/ouroboros-network/blob/83baf7eb58907137d50605fc2c85fd4c51ae68e0/ouroboros-consensus-cardano/test/Test/ThreadNet/Cardano.hs#L446-L447

which boils down to `SL.emptyPParams`.

https://github.com/input-output-hk/ouroboros-network/blob/62e57b9673e0140c87c6edd6ca8fb7b813c9f8d9/ouroboros-consensus-shelley-test/src/Test/ThreadNet/Infra/Shelley.hs#L293

File: ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs (hunk 13 above)
[the remark this answers is not in the document]
Comment (nfrisby) [reply ouroboros-consensus-cardano/test/Test/ThreadNet/TxGen/Cardano.hs:79]: Ah, I just noticed that the comment above explains it in natural language.

**Comment by nfrisby** [comment]
@nc6 Thanks for your eyes! I expanded comments a bit in response to (most of?) your questions/observations.

**Comment by nfrisby** [comment]
Doh! I currently have terrrrible wifi, so I'm unable to fetch the new deps to update my nix-shell to build locally. So I've pushed up a one line change (adding `import qualified Shelley.Spec.Ledger.OverlaySchedule as SL`). I'm hoping that suffices.

If not, I'll have to wait until the next chance I get an hour or so to kill while keeping the sleeping puppy company.

File: ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs (hunk 10 above)
[the remark this answers is not in the document]
Comment (mrBliss) [reply ouroboros-consensus-cardano/test/Test/Consensus/Cardano/MockCrypto.hs:41]: One thing to keep in mind is that real VRF will make the tests slower.

**Comment by mrBliss** [comment]
> Doh! I currently have terrrrible wifi, so I'm unable to fetch the new deps to update my nix-shell to build locally. So I've pushed up a one line change (adding `import qualified Shelley.Spec.Ledger.OverlaySchedule as SL`). I'm hoping that suffices.
> 
> If not, I'll have to wait until the next chance I get an hour or so to kill while keeping the sleeping puppy company.

You don't have to feel obligated to finish this PR during your vacation, on the contrary, ignore it completely until you're back :slightly_smiling_face:

**Comment by nfrisby** [comment]
bors retry
