### PR TITLE
Fix Peer Sharing issue #4642

### LINKED ISSUE #4642: PeerSharing negotiated even when it is disabled.
When a client signals that it supports PeerSharing, either public or private the server will simply echo the clients which. It won't take its own configuration into account.

```
{"app":[],"at":"2023-08-14T10:32:04.47Z","data":{"connectionHandler":{"agreedOptions":{"diffusionMode":"InitiatorAndResponderDiffusionMode","networkMagic":764824073,"peerSharing":"PeerSharingPublic","query":false},"kind":"HandshakeSuccess","versionNumber":11},"connectionId":{"localAddress":{"address":"1.1.1.1","port":"3001"},"remoteAddress":{"address":"1.2.2.12","port":"3001"}},"kind":"ConnectionHandler"},"env":"8.1.1:6f79e","host":"testnet-","loc":null,"msg":"","ns":["cardano.node.ConnectionManager"],"pid":"2497934","sev":"Info","thread":"858"}
```

### PR DESCRIPTION
**Pull request by bolt12**
Fixes #4642 by simplifying the `PeerSharing` options, i.e. removes `PeerSharingPrivate` making the handshake negotiation symmetric.

I also updated the wiki page to keep track of these changes on the design docs: https://github.com/input-output-hk/ouroboros-network/wiki/Peer-Sharing-Implementation-Plan#post-implementation-notes

### CODE REVIEW

**Comment by bolt12** [comment]
Yes!

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerStateActions.hs [hunk 1]
```diff
@@ -456,8 +456,8 @@ instance (Show peerAddr, Show versionData)
       "PeerConnectionHandle " ++ show pchConnectionId ++ " " ++ show pchVersionData
 
 pchPeerSharing :: (versionData -> PeerSharing)
-               -> PeerConnectionHandle muxMode responderCtx peerAddr versionData bytes m a b
-               -> PeerSharing
+                     -> PeerConnectionHandle muxMode responderCtx peerAddr versionData bytes m a b
+                     -> PeerSharing
```
Comment (bolt12) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/PeerStateActions.hs:460]: Unnecessary

File: ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs [hunk 2]
```diff
@@ -67,14 +67,12 @@ encodeRemoteAddress (SockAddrInet pn w) = CBOR.encodeListLen 3
                            <> CBOR.encodeWord 0
                            <> CBOR.encodeWord32 w
                            <> encodePortNumber pn
-encodeRemoteAddress (SockAddrInet6 pn fi (w1, w2, w3, w4) si) = CBOR.encodeListLen 8
+encodeRemoteAddress (SockAddrInet6 pn _ (w1, w2, w3, w4) _) = CBOR.encodeListLen 6
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs:70]: It should be: `encodeRemoteAddress :: NodeToNodeVersion -> SockAddr -> CBOR.Encoding`.

**Review by coot — CHANGES_REQUESTED** [review]

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 3]
```diff
@@ -149,9 +162,50 @@ nodeToNodeCodecCBORTerm version
...
+                             PeerSharingEnabled  -> 1)
+              , CBOR.TBool query
+              ]
+
+        decodeTerm :: NodeToNodeVersion -> CBOR.Term -> Either Text NodeToNodeVersionData
+        decodeTerm _ (CBOR.TList [CBOR.TInt x, CBOR.TBool diffusionMode, CBOR.TInt peerSharing, CBOR.TBool query])
+          | x >= 0
+          , x <= 0xffffffff
+          , peerSharing >= 0
+          , peerSharing <= 2
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:175]: It should be smaller or equal than `1`, isn't it?
```suggestion
          , peerSharing <= 1
```

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 4]
```diff
@@ -149,9 +162,50 @@ nodeToNodeCodecCBORTerm version
...
+                                  else InitiatorAndResponderDiffusionMode,
+                  peerSharing = case peerSharing of
+                                  0 -> PeerSharingDisabled
+                                  1 -> PeerSharingEnabled
+                                  _ -> error "decodeTerm: impossible happened!",
+                  query = query
+                }
+          | x < 0 || x > 0xffffffff
+          = Left $ T.pack $ "networkMagic out of bound: " <> show x
+          | otherwise -- peerSharing < 0 || peerSharing > 2
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:190]:
```suggestion
          | otherwise -- peerSharing < 0 || peerSharing > 1
```

File: ouroboros-network/CHANGELOG.md [hunk 5]
```diff
@@ -12,6 +12,10 @@
 
 * Fix diffusion tests
 
+* Update types to accommodate `PeerSharing` data type changes.
```
Comment (coot) [inline ouroboros-network/CHANGELOG.md:15]: This entry should explain the changes in a little more detail, e.g. how it will affect node including previous versions.

File: ouroboros-network/CHANGELOG.md [hunk 6]
```diff
@@ -12,6 +12,10 @@
...
+
+* Fix PeerSharing IPv6 enc/decoding
```
Comment (coot) [inline ouroboros-network/CHANGELOG.md:17]:
```suggestion
* Changed encoding of IPv6 addresses sent over `PeerSharing` mini-protocol.
```

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/KnownPeers.hs [hunk 7]
```diff
@@ -59,7 +59,7 @@ belowTarget actions
                         }
             }
     -- Only start Peer Sharing request if PeerSharing was enabled
-  | peerSharing /= NoPeerSharing
+  | peerSharing /= PeerSharingDisabled
```
Comment (coot) [inline ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/KnownPeers.hs:62]: Why not just a pattern match:
```suggestion
  | PeerSharingEnabled <- peerSharing
```

**Review by coot — CHANGES_REQUESTED** [review]

File: ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/KnownPeers.hs (hunk 7 above)
Comment (bolt12) [reply ouroboros-network/src/Ouroboros/Network/PeerSelection/Governor/KnownPeers.hs:62]: I tend to forget this syntax exists

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs (hunk 3 above)
Comment (bolt12) [reply ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:175]: Yes :)

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 8]
```diff
@@ -127,7 +140,7 @@ instance Acceptable NodeToNodeVersionData where
       = Accept NodeToNodeVersionData
           { networkMagic  = networkMagic local
           , diffusionMode = diffusionMode local `min` diffusionMode remote
-          , peerSharing   = peerSharing remote
+          , peerSharing   = (peerSharing local) <> (peerSharing remote)
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:143]:
```suggestion
          , peerSharing   = peerSharing local <> peerSharing remote
```

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 9]
```diff
@@ -268,6 +273,93 @@ nodeToNodeCodecCBORTerm version
 data ConnectionMode = UnidirectionalMode | DuplexMode
 
 
+encodePortNumber :: PortNumber -> CBOR.Encoding
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:276]: Let's move this to `PeerSharing.Codec`.

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 10]
```diff
@@ -268,6 +273,93 @@ nodeToNodeCodecCBORTerm version
...
+        return (SockAddrInet pn w)
+      1 -> do
+        w1 <- CBOR.decodeWord32
+        w2 <- CBOR.decodeWord32
+        w3 <- CBOR.decodeWord32
+        w4 <- CBOR.decodeWord32
+        fi <- CBOR.decodeWord32
+        si <- CBOR.decodeWord32
+        pn <- decodePortNumber
+        return (SockAddrInet6 pn fi (w1, w2, w3, w4) si)
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:360]:
```suggestion
        return (SockAddrInet6 pn 0 (w1, w2, w3, w4) 0)
```

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 11]
```diff
@@ -268,6 +273,93 @@ nodeToNodeCodecCBORTerm version
...
+        w <- CBOR.decodeWord32
+        pn <- decodePortNumber
+        return (SockAddrInet pn w)
+      1 -> do
+        w1 <- CBOR.decodeWord32
+        w2 <- CBOR.decodeWord32
+        w3 <- CBOR.decodeWord32
+        w4 <- CBOR.decodeWord32
+        fi <- CBOR.decodeWord32
+        si <- CBOR.decodeWord32
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:358]:
```suggestion
        _fi <- CBOR.decodeWord32
        _si <- CBOR.decodeWord32
```

File: ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs [hunk 12]
```diff
@@ -32,69 +23,41 @@ data PeerSharing = PeerSharingDisabled -- ^ Peer does not participate in Peer Sh
...
+
+instance FromJSON PeerSharing where
+  parseJSON = withText "PeerSharing" $ \t ->
+    case readMaybe (Text.unpack t) of
+      Nothing -> fail ("PeerSharing.parseJSON: could not parse value: "
+                     ++ Text.unpack t)
+      Just ps -> return ps
+
+instance ToJSON PeerSharing where
+  toJSON = String . Text.pack . show
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs:62]: These instances should go to `cardano-node`.

**Comment by bolt12** [comment]
Test

**Comment by bolt12** [comment]
test

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 13]
```diff
@@ -149,9 +154,50 @@ nodeToNodeCodecCBORTerm version
...
+          = Right
+              NodeToNodeVersionData {
+                  networkMagic = NetworkMagic (fromIntegral x),
+                  diffusionMode = if diffusionMode
+                                  then InitiatorOnlyDiffusionMode
+                                  else InitiatorAndResponderDiffusionMode,
+                  peerSharing = case peerSharing of
+                                  0 -> PeerSharingDisabled
+                                  1 -> PeerSharingEnabled
+                                  _ -> error "decodeTerm: impossible happened!",
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:177]: Sam was recently rewriting our code to avoid `error` calls, we can also avoid it if we change the way we guard & pattern match.

File: ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing/Codec.hs [hunk 14]
```diff
@@ -0,0 +1,100 @@
...
+
+decodePortNumber :: CBOR.Decoder s PortNumber
+decodePortNumber = fromIntegral <$> CBOR.decodeWord16
+
+
+-- | This encoder should be faithful to the PeerSharing
+-- CDDL Specification.
+--
+-- See the network design document for more details
+--
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing/Codec.hs:25]:
```suggestion
--
-- /Invariant:/ not a unix socket address type.
--
```

File: ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs [hunk 15]
```diff
@@ -141,8 +141,9 @@ data ConnectionManagerArguments handlerTrace socket peerAddr handle handleError
         cmPrunePolicy         :: PrunePolicy peerAddr (STM m),
         cmConnectionsLimits   :: AcceptedConnectionsLimit,
 
-        -- | How to extract PeerSharing information from versionData
-        cmGetPeerSharing      :: versionData -> PeerSharing
+        -- | How to extract remote side's PeerSharing information from
+        -- versionData
+        cmGetPeerSharing :: versionData -> PeerSharing
```
Comment (coot) [inline ouroboros-network-framework/src/Ouroboros/Network/ConnectionManager/Core.hs:146]:
```suggestion
        cmGetPeerSharing      :: versionData -> PeerSharing
```

File: ouroboros-network-protocols/CHANGELOG.md [hunk 16]
```diff
@@ -14,6 +14,12 @@
 * Add a 3673s timeout to chainsync's StIdle state.
 * Add a 97s timeout to keepalive's StClient state.
 
+* Add a test to check that Peer Sharing values after handshake are symmetric
+  relative to the initiator and responder side.
+* Adds cddl specs and tests for `NodeToNodeV_13` and handshake
+
+* Refactored cddl tests for `PeerSharing` to include versioning.
```
Comment (coot) [inline ouroboros-network-protocols/CHANGELOG.md:21]:
```suggestion
* Added a test to check that Peer Sharing values after handshake are symmetric
  relative to the initiator and responder side.
* Added cddl specs and tests for `NodeToNodeV_13` and handshake

* Refactored cddl tests for `PeerSharing` to include versioning.
```

File: ouroboros-network-protocols/test-cddl/Main.hs [hunk 17]
```diff
@@ -700,20 +763,28 @@ instance Arbitrary NodeToNodeVersionData where
         <*> oneof [ pure InitiatorOnlyDiffusionMode
                   , pure InitiatorAndResponderDiffusionMode
                   ]
-        <*> oneof [ pure NoPeerSharing
-                  , pure PeerSharingPrivate
-                  , pure PeerSharingPublic
-                  ]
+        <*> elements [ PeerSharingDisabled
+                     , PeerSharingEnabled
+                    ]
```
Comment (coot) [inline ouroboros-network-protocols/test-cddl/Main.hs:768]:
```suggestion
        <*> elements [ PeerSharingDisabled
                     , PeerSharingEnabled
                     ]
```

File: ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs [hunk 18]
```diff
@@ -971,6 +983,63 @@ prop_query_version createChannels codec versionDataCodec clientVersions serverVe
...
+        clientVersions)
+      (handshakeServerPeer
+        versionDataCodec
+        acceptableVersion
+        queryVersion
+        serverVersions)
+  pure $ case (clientRes, serverRes) of
+    (  Right (HandshakeNegotiationResult _ v (ArbitraryNodeToNodeVersionData clientResult))
+     , Right (HandshakeNegotiationResult _ v' (ArbitraryNodeToNodeVersionData serverResult))
+     ) | v == v'
```
Comment (coot) [inline ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs:1015]: it's a bit strange that `runConnectedPeers` returns a pair of `ArbitraryNodeToNodeVersionData` rather than a pair of `NodeToNodeVersionData`.

File: ouroboros-network/CHANGELOG.md [hunk 19]
```diff
@@ -6,6 +6,19 @@
 
 ### Non-breaking changes
 
+- Update types to accommodate `PeerSharing` data type changes.
```
Comment (coot) [inline ouroboros-network/CHANGELOG.md:9]: Just to be consistent with other entries
```suggestion
* Update types to accommodate `PeerSharing` data type changes.
```

File: ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs [hunk 20]
```diff
@@ -46,21 +42,13 @@ instance FromJSON PeerSharing where
...
-combinePeerInformation :: PeerSharing -> PeerAdvertise -> PeerSharing
-combinePeerInformation NoPeerSharing      _                  = NoPeerSharing
-combinePeerInformation PeerSharingPrivate _                  = PeerSharingPrivate
-combinePeerInformation PeerSharingPublic  DoNotAdvertisePeer = PeerSharingPrivate
-combinePeerInformation _                         _           = PeerSharingPublic
+-- 'PeerSharingDisabled' is the absorbing element
+combinePeerSharing :: PeerSharing -> PeerSharing -> PeerSharing
+combinePeerSharing PeerSharingDisabled _ = PeerSharingDisabled
+combinePeerSharing _ PeerSharingDisabled = PeerSharingDisabled
+combinePeerSharing _ _                   = PeerSharingEnabled
```
[the remark this answers is not in the document]
Comment (coot) [reply ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing.hs:29]: I'd inlined this in the `Semigroup` instance.

**Review by coot — CHANGES_REQUESTED** [review]

File: ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs (hunk 18 above)
Comment (bolt12) [reply ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs:1015]: Yes, I was just lazy not to massage the data types, `ArbitraryNodeToNodeVersionData` has an Acceptable instance so it just works

File: ouroboros-network-api/CHANGELOG.md [hunk 21]
```diff
@@ -4,6 +4,12 @@
 
 ### Breaking changes
 
+- Remote `PeerSharingPrivate` option from the `PeerSharing` data type.
```
Comment (karknu) [inline ouroboros-network-api/CHANGELOG.md]: s/Remote/Remove

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs [hunk 22]
```diff
@@ -149,35 +154,79 @@ nodeToNodeCodecCBORTerm version
...
+          , Just ps <- case peerSharing of
+                        0 -> Just PeerSharingDisabled
+                        1 -> Just PeerSharingEnabled
+                        _ -> Nothing
+          = Right
+              NodeToNodeVersionData {
+                  networkMagic = NetworkMagic (fromIntegral x),
+                  diffusionMode = if diffusionMode
+                                  then InitiatorOnlyDiffusionMode
+                                  else InitiatorAndResponderDiffusionMode,
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:175]: This is out of the scope, but we should rename `diffusionMode` field as `initiatorOnlyMode` otherwise it's a bit confusing. I created an issue for it #4708.

File: ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing/Codec.hs [hunk 23]
```diff
@@ -0,0 +1,102 @@
...
+                        <> encodePortNumber pn
+      SockAddrInet6 pn fi (w1, w2, w3, w4) si -> CBOR.encodeListLen 8
+                                            <> CBOR.encodeWord 1
+                                            <> CBOR.encodeWord32 w1
+                                            <> CBOR.encodeWord32 w2
+                                            <> CBOR.encodeWord32 w3
+                                            <> CBOR.encodeWord32 w4
+                                            <> CBOR.encodeWord32 fi
+                                            <> CBOR.encodeWord32 si
+                                            <> encodePortNumber pn
```
Comment (coot) [inline ouroboros-network-api/src/Ouroboros/Network/PeerSelection/PeerSharing/Codec.hs:58]:
```suggestion
      SockAddrInet6 pn fi (w1, w2, w3, w4) si -> CBOR.encodeListLen 8
                                              <> CBOR.encodeWord 1
                                              <> CBOR.encodeWord32 w1
                                              <> CBOR.encodeWord32 w2
                                              <> CBOR.encodeWord32 w3
                                              <> CBOR.encodeWord32 w4
                                              <> CBOR.encodeWord32 fi
                                              <> CBOR.encodeWord32 si
                                              <> encodePortNumber pn
```

File: ouroboros-network-protocols/CHANGELOG.md [hunk 24]
```diff
@@ -16,6 +16,12 @@
 * Add a 3673s timeout to chainsync's StIdle state.
 * Add a 97s timeout to keepalive's StClient state.
 
+* Added a test to check that Peer Sharing values after handshake are symmetric
+  relative to the initiator and responder side.
+* Added cddl specs and tests for `NodeToNodeV_13` and handshake
+
+* Refactored cddl tests for `PeerSharing` to include versioning.
```
Comment (coot) [inline ouroboros-network-protocols/CHANGELOG.md:23]:
```suggestion
* Refactored cddl tests for `PeerSharing` to take into account versioning.
```

File: ouroboros-network/CHANGELOG.md [hunk 25]
```diff
@@ -6,6 +6,19 @@
...
+* Introduce NodeToNodeVersion 13
+* Update types to accommodate `PeerSharing` data type changes:
+  * `PeerSharingPrivate` got removed and hence, handshake is now symmetric,
+  fixing issue [#4642](https://github.com/input-output-hk/ouroboros-network/issues/4642)
+  * This implies that newer peer sharing node versions will see older
+  version's `PeerSharingPrivate` as `PeerSharingEnabled`. So older version
+  node's should not rely on `PeerSharingPrivate` semantics from newer version
+  honest nodes.
+
+* Changed encoding of IPv6 addresses sent over `PeerSharing` mini-protocol.
```
Comment (coot) [inline ouroboros-network/CHANGELOG.md:20]: I like to write the change log entries using: `updated ..., fixed, ...` rather than `update ..., fix ...`; the same makes more sense in commits.

File: ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Diffusion/Node.hs [hunk 26]
```diff
@@ -366,23 +368,25 @@ run blockGeneratorArgs limits ni na tracersExtra tracerBlockFetch =
...
-
-          CBOR.TList [CBOR.TBool True, CBOR.TInt 0] -> Right (NtNVersionData InitiatorAndResponderDiffusionMode NoPeerSharing)
-          CBOR.TList [CBOR.TBool True, CBOR.TInt 1] -> Right (NtNVersionData InitiatorAndResponderDiffusionMode PeerSharingPrivate)
-          CBOR.TList [CBOR.TBool True, CBOR.TInt 2] -> Right (NtNVersionData InitiatorAndResponderDiffusionMode PeerSharingPublic)
-          _                -> Left (Text.pack "unversionedDataCodec: unexpected term")
+            InitiatorOnlyDiffusionMode         ->
+              let peerSharing = case ntnPeerSharing of
+                    PeerSharingDisabled -> 0
+                    PeerSharingEnabled  -> 1
+               in CBOR.TList [CBOR.TBool False, CBOR.TInt peerSharing]
```
Comment (coot) [inline ouroboros-network/sim-tests-lib/Test/Ouroboros/Network/Diffusion/Node.hs:375]: we could move this out of the case to cover both cases at the same time.

**Review by coot — APPROVED** [review]
LGTM, just a few minor remarks.

File: ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs (hunk 18 above)
Comment (coot) [reply ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/Handshake/Test.hs:1015]: If you don't want to do that now, please leave a TODO / issue to refactor this later.

File: ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs (hunk 22 above)
Comment (bolt12) [reply ouroboros-network-api/src/Ouroboros/Network/NodeToNode/Version.hs:175]: Thank you!
