### PR TITLE
Avoid ChainDB Iterator and Reader leaks with a ResourceRegistry

### LINKED ISSUE #896: Chain DB: close iterators and readers when an exception is thrown
The iterators and readers that the ChainDB provides must be closed after use, otherwise file handles will be leaked. We already fixed (hopefully all) leaks (#859 #891) that happen in regular circumstances, but we don't deal with **exceptional** circumstances. Unfortunately, we can't simply use `bracket` because we are using the iterators and readers in non-scoped contexts, e.g., the `BlockFetchServer` and the `ChainSyncServer`. We will probably need something like `ResourceT`.

### PR DESCRIPTION
**Pull request by mrBliss**
Closes #896.

To obtain a ChainDB iterator or reader, a `ResourceRegistry` must be passed.
That `ResourceRegistry` will be used to register all ImmutableDB iterators it
opens. These iterators hold on to file handles and are the ones we don't want
to leak when an exception is thrown.

The `ProtocolHandlers` that use ChainDB iterators (`BlockFetchServer`) and
readers (`ChainSyncServer`) now take a `ResourceRegistry` as an argument. When
the protocol thread starts, the registry is created and when the thread
terminates, because of normal termination or because an exception is thrown,
the registry is closed, running the clean-up of the registered resources.

At the end of the ChainDB q-s-m test, we check that no clean-up actions are
still registered after shutting down the ChainDB (which closes all open
iterators and readers).

### CODE REVIEW

**Comment by mrBliss** [comment]
@coot I added you as a reviewer to inform you about the changes I intend to make to `Ouroboros.Consensus.NodeNetwork`.

File: ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs [hunk 1]
```diff
@@ -293,6 +296,24 @@ appendBlock db@ImmDB{..} b = withDB db $ \imm -> case isEBB b of
...
+registeredStream :: (MonadMask m, MonadSTM m, HasHeader blk)
+                 => ImmDB m blk
+                 -> ResourceRegistry m
+                 -> Maybe (SlotNo, HeaderHash blk)
+                 -> Maybe (SlotNo, HeaderHash blk)
+                 -> m (ImmDB.Iterator (HeaderHash blk) m Lazy.ByteString)
+registeredStream db registry start end = mask $ \unmask -> do
+    it  <- unmask $ withDB db $ \imm -> ImmDB.streamBinaryBlobs imm start end
+    key <- register registry (iteratorClose db it)
+    return it
```
Comment (edsko) [inline ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs]: Let's add a comment here. Adding this to the close action of the iterator is not crucial for correctness, but it avoids the resource registry growing too much.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Storage/ChainDB/Impl/ImmDB.hs]: Also, let's introduce the equivalent of [allocate](http://hackage.haskell.org/package/resourcet-1.2.2/docs/Control-Monad-Trans-Resource.html#v:allocate) so that this `mask` dance happens once and for all in the resource registry.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+      key
+      cleanup
+    return $ ResourceKey key
+
+-- | Unregister a resource that already has been cleaned up. It will no longer
+-- be cleaned up when the 'ResourceRegistry' is closed.
+unregister :: MonadSTM m => ResourceRegistry m -> ResourceKey -> m ()
+unregister ResourceRegistry { _registered } (ResourceKey key) = atomically $
+    modifyTVar' _registered $ \m ->
+      assert (IntMap.member key m) $ IntMap.delete key m
```
[the remark this answers is not in the document]
Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: Let's make it the equivalent of [release](http://hackage.haskell.org/package/resourcet-1.2.2/docs/Control-Monad-Trans-Resource.html#v:release) instead (i.e., also executing the action _if_ needed).

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+
+-- | Create new resource registry.
+new :: MonadSTM m => m (ResourceRegistry m)
+new = atomically $ do
+    _registered <- newTVar IntMap.empty
+    _nextKey    <- newTVar minBound
```
Comment (edsko) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: Let's start at `1` instead.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+--
+-- After closing a 'ResourceRegistry', it should no longer be used. This means
+-- that a 'ResourceRegistry' can only be closed once.
+close :: (MonadSTM m, MonadMask m) => ResourceRegistry m -> m ()
+close ResourceRegistry { _registered } = do
+    cleanups <- atomically $ do
+      cleanups <- IntMap.elems <$> readTVar _registered
+      writeTVar _registered $ error msg
+      return cleanups
+    mask $ \_unmask -> forM_ cleanups $ \cleanup ->
```
Comment (edsko) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: There is `mask_`.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: Let's document that all cleanup handlers are run with exceptions masked. Depending on the resources managed, this may or may not be time consuming.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: Let's not swallow exceptions: let's try to cleanup as much as we can, and if any of those throws an exception, pick an arbitrary (the first, say) one to rethrow -- we probably don't expect these exceptions, so if they arise, that might be indicative of a bug.

File: ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs [hunk 5]
```diff
@@ -1050,18 +1060,24 @@ prop_sequential = forAllCommands smUnused Nothing $ \cmds -> QC.monadicIO $ do
         realChain' <- toChain db'
         closeDB db'
 
-        ThreadRegistry.cancelAll registry
+        ThreadRegistry.cancelAll threadRegistry
+
+        -- closeDB should have closed all open Readers and Iterators, freeing
+        -- up all resources, so there should be no more clean-up actions left.
+        remainingCleanups <- ResourceRegistry.nbCleanups resourceRegistry
```
Comment (edsko) [inline ouroboros-consensus/test-storage/Test/Ouroboros/Storage/ChainDB/StateMachine.hs]: Let's document that `remainingCleanups` is expected to be zero only because we don't currently test with any exceptions. If this was _always_ true the registry would not be necessary in the first place. 

Perhaps we _should_ actually modify the tests so that some exceptions are thrown, thereby testing the registry..? :thinking:

**Comment by mrBliss** [comment]
C'mon bors, it's been more than an hour already...
