### PR TITLE
consensus: handle EBBs in rewindHeaderState

### LINKED ISSUE #1690: bug in `rewindHeaderState` triggered by EBBs
https://github.com/input-output-hk/ouroboros-network/blob/599afc730af5f8d64accc6ab1c8d05bdb27ee7d8/ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs#L200-L209

If `p` is an EBB with a proper block in the same slot, then the `annTipPoint t > p` is correct only half of the time: it will either correctly rewind the tips to the EBB or it will incorrectly also retain the proper block, depending on how the hashes happen to compare.

### PR DESCRIPTION
**Pull request by nfrisby**
Fixes #1690.

I believe this bug was masked by Issue #1489; I discovered it and confirmed that this patch fixes it on my related WIP branch. This PR does not include a repro for this bug, but that branch does, and PR #1506 will as soon as I'm able to update it with that WIP branch -- that's my current focus.

### CODE REVIEW

File: ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs [hunk 1]
```diff
@@ -201,12 +201,13 @@ rewindHeaderState cfg p HeaderState{..} = do
...
     return $ HeaderState {
         headerStateChain  = chainState'
-      , headerStateTips   = Seq.dropWhileR rolledBack headerStateTips
+      , headerStateTips   = Seq.dropWhileR rollBack headerStateTips
       , headerStateAnchor = headerStateAnchor
       }
   where
-    rolledBack :: AnnTip blk -> Bool
-    rolledBack t = annTipPoint t > p
+    rollBack :: AnnTip blk -> Bool
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs]: The name change was accidental, but doesn't seem worth another force push :)

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs]: Did you see https://github.com/input-output-hk/ouroboros-network/issues/1690#issuecomment-590699588?

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/HeaderValidation.hs]: I did now. I've adopted it.

**Comment by edsko** [comment]
@nfrisby feel free to `bors` this once you feel confident it solves the problem :)

**Comment by nfrisby** [comment]
My big update to PR #1506 is still a work-in-progress, but I do think it is not "feature complete" with respect to PBFT and RealPBFT. In particular the commit on this PR passed hundreds of thousands of tests (though I can't be sure how many exercised it), including a couple repros derived from this PR's Issue.

So I'm going to merge. Thanks.
