### PR TITLE
Return a numeric error code for the exceptions that will be thrown

### LINKED ISSUE #1201: Inform Daedalus about fatal exceptions and what to do
Similar to #1200. If a fatal exception is thrown, the Daedalus wallet should respond correctly to this, e.g., by triggering a full recovery.

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1201.

The node will use this `ExitFailure`s in the `toplevelExceptionHandler` (in
`cardano-node`) to report to the wallet why it failed. Based on the
`ExitFailure` code, the wallet can give a more useful error message and
perform (or instruct the user to perform) the right action.

### CODE REVIEW

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+--
+-- For example, for PBFT, it could be that the block signing key and the
+-- delegation certificate do not match.
+configurationError :: ExitFailure
+configurationError = 2
+
+-- | There is a problem with the network connection, the user should
+-- investigate.
+--
+-- TODO We're not yet returning this.
```
Comment (mrBliss) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: @coot @karknu Which exception would the network layer throw when there is a network connection error?

Comment (dcoutts) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: We could have internal "impossible" errors, but none expected due to a bad network connection. Those would not be fatal for the node.

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs [hunk 2]
```diff
@@ -0,0 +1,127 @@
+{-# LANGUAGE LambdaCase          #-}
+{-# LANGUAGE NamedFieldPuns      #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+module Ouroboros.Consensus.Node.ExitFailure
+  ( -- * Pre-defined ExitFailurse
```
Comment (intricate) [inline ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]:
```suggestion
  ( -- * Pre-defined ExitFailures
```

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: Thanks for catching :+1:

File: ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs (hunk 1 above)
Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: My thinking is that when the node is started without a working internet connection, it should be reported to the wallet so that it can give some useful instructions to the user instead of some cryptic (to most non-developers) error message. Would the lack of a working internet connection result in a `MuxError` or would it just time out and retry continuously?

How do you suggest we report such issues to the wallet?

Maybe it's best to remove that case from this PR for now and let you guys come up with a better way to report network connectivity issues?

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: Can't we leave the error code and decide later on how to actually detect this?

Comment (mrBliss) [reply ouroboros-consensus/src/Ouroboros/Consensus/Node/ExitFailure.hs]: Good idea. This means we can merge as is.
