### PR TITLE
More explicit resource management in ChainSync client and server

### LINKED ISSUE #2892: Introduce the `bracketWithRegistry` combinator
During the post mortem for Issue #2870, we invented an idea to help prevent it in the future. That bug was due to confusion caused by the fact that we allocated a `registry` and also a narrower-manager (a `ChainDB` `Reader`/`Follower`) that in turn used that registry, but did not register itself in that registry, despite the registry and the manager having the same lifetime. We incorrectly assumed that `newReader` registered itself in the registry that it was passed.

So we're going to introduce a `ResourceRegistry` combinator for use in this situation, where a `bracket`-ed thing and a registry it needs share the same lifetime. This will let us be very explicit about that coincident lifetime, which should make it very obvious if future changes cause the lifetimes to become different.

### PR DESCRIPTION
**Pull request by nfrisby**
Fixes #2892.

### CODE REVIEW

**Comment by nfrisby** [comment]
@edsko This is what we talked about on Wednesday; let's scan it on our Friday call.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 1]
```diff
@@ -587,6 +588,32 @@ releaseResources rr keys releaser = do
...
+     -- not themselves registered, since they're simply 'bracket'ed.
+  -> (a -> m ())
+     -- ^ Release the bracketed resources.
+  -> (ResourceRegistry m -> a -> m r)
+  -> m r
+bracketWithRegistry newA closeA body =
+    -- It would be OK to fuse these two calls to 'bracket', but it's simpler and
+    -- less error-prone this way.
+    withRegistry $ \registry ->
+      bracket (newA registry) closeA $ \a ->
```
Comment (kderme) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: I noticed this pr and #2892 while working on some changes at the ChainSync that we need for db-sync. I think in general blending brackets and registries can be tricky, basically because of the order of deallocation. Here `a` will be freed before anything else allocated with the registry. By using a simple registry instead, things are freed from younger to older.

Comment (kderme) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: I'm not sure if this is a real issue for Reader/Follower, but may be worth at least documenting it for `bracketWithRegistry`.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: The point is that this is a _new_ registry: we are constructing something that for some reason needs a registry (example: the reader), but really the scope of that thing and the registry are coupled. Notice that _nothing else_ has access to this registry: the only thing that has access to it is the new resource itself. Hence, deallocating that resource before anything else in the registry is okay. 

What you are saying is true nonetheless: _if_ we then later allocate a new resource that somehow refers to this new resource (i.e., a reference in the reverse direction), we might be in trouble. That kind of "cyclic dependency" graph would indeed be potentially problematic.

Comment (kderme) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: Yes this is the usual case: newer resources reference older resources. That's why the younger to older deallocation that's done by Registry is the normal thing to do. And it's a kinda violated by the bracket.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: Yes, you are correct. It would indeed be good to state the side condition here: those newer conditions should not be referring to the resources that is allocated by this new abstraction.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: The point is that the lifetime of this new resource _is equal to_ the lifetime of the registry.

Comment (edsko) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: Good observation!

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 2]
```diff
@@ -587,6 +588,32 @@ releaseResources rr keys releaser = do
...
+     -- ^ Allocate the bracketed resources. They depend on the registry but are
+     -- not themselves registered, since they're simply 'bracket'ed.
+  -> (a -> m ())
+     -- ^ Release the bracketed resources.
+  -> (ResourceRegistry m -> a -> m r)
+  -> m r
+bracketWithRegistry newA closeA body =
+    -- It would be OK to fuse these two calls to 'bracket', but it's simpler and
+    -- less error-prone this way.
+    withRegistry $ \registry ->
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:613]: We can side-step the precondition that @kderme's noticed (nice catch!) by simply allocating the `a` in the registry. This combinator ensures it's the oldest thing in the registry, and so it will be deallocated last.

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:613]: Also rename to `brackWithPrivateRegistry` and remove the `registry` argument from the `body`: none of our uses cases need it yet, so let's simplify at least for now.

The fact that none of our use cases need it yet suggested that perhaps `newFollower` should simply be replaced with `withFollower`, but it turns out that the QSM tests need the `newFollower` variant, since QSM inherently uses a flat sequence of commands: we'd have no hook into QSM in which to call `withFollower` with a scope other than "the whole test case".

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs [hunk 3]
```diff
@@ -132,3 +102,83 @@ simStateT stVar (Sim k) = Sim $ \(StateT f) -> do
...
+  , wInitial     :: Maybe fp
+    -- | An action executed each time the fingerprint changes.
+  , wNotify      :: a -> m ()
+    -- | The variable to monitor.
+  , wReader      :: STM m a
+  }
+
+-- | An existentially quantified 'Watcher'.
+--
+-- It's sometimes convenient to forget the unnecessary type variables.
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs:132]: Eliminate `SomeWatcher`; just include the types in the use-case.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs [hunk 4]
```diff
@@ -132,3 +102,83 @@ simStateT stVar (Sim k) = Sim $ \(StateT f) -> do
...
+data SomeWatcher m where
+  SomeWatcher :: Eq fp => !(Watcher m a fp) -> SomeWatcher m
+
+-- | Execute a 'Watcher'
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs:136]: Add NOT EXPORTED to comment.

File: ouroboros-consensus/src/Ouroboros/Consensus/BlockchainTime/API.hs [hunk 5]
```diff
@@ -67,9 +67,14 @@ onKnownSlotChange :: forall m. (IOLike m, HasCallStack)
                   -> String            -- ^ Label for the thread
                   -> (SlotNo -> m ())  -- ^ Action to execute
                   -> m (m ())
-onKnownSlotChange registry btime label =
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/BlockchainTime/API.hs:70]: Switch this to be `Watcher`; the usesites will choose how to manage the thread.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs [hunk 6]
```diff
@@ -132,3 +102,83 @@ simStateT stVar (Sim k) = Sim $ \(StateT f) -> do
...
+spawnWatcher registry label watcher =
+    forkLinkedThread registry label $ runWatcher watcher
+
+-- | Spawn a new thread that runs a 'Watcher'
+--
+-- The thread is bracketed via 'withAsync' and 'link'ed.
+withWatcher :: forall m a fp r. (IOLike m, Eq fp, HasCallStack)
+            => String    -- ^ Label for the thread
+            -> Watcher m a fp
+            -> (Async m Void -> m r)
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs:179]: Drop `Async` argument from callback.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs (hunk 2 above)
Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:613]: Edsko and I discussed going farther and not passing the `registry` to the body. However, I just realized that the `a` type variable could be abused to pass the registry to the body.

So I'll still make no assumptions about orderings: we'll allocate the "bracketed resources" (via `newA`) in the registry.

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:613]: I also just realized that the `newA` argument might itself allocate something in the registry. This would be weird, but allowed by is allowed by the types so far. I'm about to push commits that use `m (ResourceRegistry m -> a)` instead, which prevents that possibility at the cost of a slightly more refactoring.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 7]
```diff
@@ -585,7 +586,49 @@ releaseResources rr keys releaser = do
 --
 -- See documentation of 'ResourceRegistry' for a detailed discussion.
 withRegistry :: (IOLike m, HasCallStack) => (ResourceRegistry m -> m a) -> m a
-withRegistry = bracket unsafeNewRegistry closeRegistry
+withRegistry body =
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:589]: Too pedantic?

File: ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs [hunk 8]
```diff
@@ -349,8 +349,10 @@ forkBlockForging
     -> BlockForging m blk
     -> m ()
 forkBlockForging maxTxCapacityOverride IS{..} blockForging =
-    void $ onKnownSlotChange registry btime threadLabel $
-        withEarlyExit_ . go
+    void
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs:352]: Contrary to existing module style? Or even global exception to style guide?

File: ouroboros-consensus-test/test-consensus/Test/Consensus/BlockchainTime/Simple.hs [hunk 9]
```diff
@@ -293,24 +294,23 @@ testOverrideDelay :: forall m. (IOLike m, MonadTime m, MonadDelay (OverrideDelay
                   -> Int  -- ^ Number of slots to collect
                   -> OverrideDelay m [SlotNo]
 testOverrideDelay systemStart slotLength maxClockRewind numSlots = do
-    result <- withRegistry $ \registry -> do
+    withRegistry $ \registry -> do
       time <- simpleBlockchainTime
```
Comment (nfrisby) [inline ouroboros-consensus-test/test-consensus/Test/Consensus/BlockchainTime/Simple.hs:298]: Check whether `simpleBlockchainTime` could be `withBlockchainTime` etc.

File: ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs (hunk 8 above)
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs:352]: Indent `void`

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/NodeKernel.hs:352]: Indent `void`; $ is binop

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs [hunk 10]
```diff
@@ -3,14 +3,18 @@
 {-# LANGUAGE DeriveGeneric              #-}
 {-# LANGUAGE DerivingStrategies         #-}
 {-# LANGUAGE FlexibleContexts           #-}
+{-# LANGUAGE GADTs                      #-}
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/STM.hs:6]: Remove this

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 11]
```diff
@@ -585,7 +586,49 @@ releaseResources rr keys releaser = do
...
+-- o The bracketed resources are older than everything in the registry.
+--
+-- In particular, this combinator closes the registry before releasing the
+-- bracketed resources, since any objects still in the registry will be younger
+-- than the bracketed resources and so may rely on them in their releasers.
+--
+-- See documentation of 'ResourceRegistry' for a more general discussion.
+bracketWithRegistry ::
+     (IOLike m, HasCallStack)
+  => m (ResourceRegistry m -> a)
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:614]: Add TODO about Issue #2897; we can widen this argument once that's fixed.

**Review by edsko — APPROVED** [review]
Subtle stuff, as always with the registry. Thanks for your observation @kderme , and well-spotted on the more general problem @nfrisby . 

Peer-reviewed this over meet; good to go after some minor cleanup, the more general problem will be addressed separately.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs [hunk 12]
```diff
@@ -585,7 +586,49 @@ releaseResources rr keys releaser = do
...
+     -- ^ Allocate the bracketed resources. They depend on the registry but are
+     -- not themselves registered.
+  -> (a -> m ())
+     -- ^ Release the bracketed resources.
+  -> (ResourceRegistry m -> a -> m r)
```
Comment (nfrisby) [inline ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs:619]: Edsko clarified: we're removing this argument to the body because this combinator captures the intent of providing a bracketed thing that happens to need a registry. That registry is private. NB if the body also needs a registry, it can allocate its own. NB number 2: a prompt invocation of close for `a` could also close the registry.

Ideally we'd write `withFollower`, and `withFollower` would be defined via `withRegistry`, which would guarantee that it's private. This combinator is intended as a generalization of `withFollower` that can be used with any allocation function that expected a privately owned registry. (But we don't think an `ST` style existential type is worthwhile.)

Something like "This combinator provides a private repository. If the allocator does not leak the registry, then it will remain private."

File: ouroboros-consensus-test/test-consensus/Test/Consensus/BlockchainTime/Simple.hs (hunk 9 above)
Comment (nfrisby) [reply ouroboros-consensus-test/test-consensus/Test/Consensus/BlockchainTime/Simple.hs]: I did change this to `bracketWithPrivateRegistry`. It's a bit odd when there's no close function for the `btime`, but it's still better capturing the intent.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs (hunk 1 above)
Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: > The point is that the lifetime of this new resource is equal to the lifetime of the registry.

For future reference, there are some minor caveats to that; see the comment on `bracketWithPrivateRegistry`.

File: ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs (hunk 2 above)
Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: We backed out those new commits. We're allowing `newA` to allocate things in the registry. (I don't think it'd even _need_ to do that, since it could just close them in the `closeA`. But that might require extensions to the `a` interface.)

Comment (nfrisby) [reply ouroboros-consensus/src/Ouroboros/Consensus/Util/ResourceRegistry.hs]: And because `newA` may allocate resources that'll be younger than the `a` bracketed here, we must track `a` in the registry; we can't close it separate from the registry because the registry has some older than `a` and some younger than `a` resources.
